package com.jzfq.rms.product.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CheckItemsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public CheckItemsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCheckItemIdIsNull() {
            addCriterion("`check_item_id` is null");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdIsNotNull() {
            addCriterion("`check_item_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdEqualTo(Integer value) {
            addCriterion("`check_item_id` =", value, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdNotEqualTo(Integer value) {
            addCriterion("`check_item_id` <>", value, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdGreaterThan(Integer value) {
            addCriterion("`check_item_id` >", value, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`check_item_id` >=", value, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdLessThan(Integer value) {
            addCriterion("`check_item_id` <", value, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("`check_item_id` <=", value, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdIn(List<Integer> values) {
            addCriterion("`check_item_id` in", values, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdNotIn(List<Integer> values) {
            addCriterion("`check_item_id` not in", values, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdBetween(Integer value1, Integer value2) {
            addCriterion("`check_item_id` between", value1, value2, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`check_item_id` not between", value1, value2, "checkItemId");
            return (Criteria) this;
        }

        public Criteria andCheckItemsIsNull() {
            addCriterion("`check_items` is null");
            return (Criteria) this;
        }

        public Criteria andCheckItemsIsNotNull() {
            addCriterion("`check_items` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckItemsEqualTo(Integer value) {
            addCriterion("`check_items` =", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsNotEqualTo(Integer value) {
            addCriterion("`check_items` <>", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsGreaterThan(Integer value) {
            addCriterion("`check_items` >", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsGreaterThanOrEqualTo(Integer value) {
            addCriterion("`check_items` >=", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsLessThan(Integer value) {
            addCriterion("`check_items` <", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsLessThanOrEqualTo(Integer value) {
            addCriterion("`check_items` <=", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsIn(List<Integer> values) {
            addCriterion("`check_items` in", values, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsNotIn(List<Integer> values) {
            addCriterion("`check_items` not in", values, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsBetween(Integer value1, Integer value2) {
            addCriterion("`check_items` between", value1, value2, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsNotBetween(Integer value1, Integer value2) {
            addCriterion("`check_items` not between", value1, value2, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueIsNull() {
            addCriterion("`check_item_value` is null");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueIsNotNull() {
            addCriterion("`check_item_value` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueEqualTo(String value) {
            addCriterion("`check_item_value` =", value, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueNotEqualTo(String value) {
            addCriterion("`check_item_value` <>", value, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueGreaterThan(String value) {
            addCriterion("`check_item_value` >", value, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueGreaterThanOrEqualTo(String value) {
            addCriterion("`check_item_value` >=", value, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueLessThan(String value) {
            addCriterion("`check_item_value` <", value, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueLessThanOrEqualTo(String value) {
            addCriterion("`check_item_value` <=", value, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueLike(String value) {
            addCriterion("`check_item_value` like", value, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueNotLike(String value) {
            addCriterion("`check_item_value` not like", value, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueIn(List<String> values) {
            addCriterion("`check_item_value` in", values, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueNotIn(List<String> values) {
            addCriterion("`check_item_value` not in", values, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueBetween(String value1, String value2) {
            addCriterion("`check_item_value` between", value1, value2, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemValueNotBetween(String value1, String value2) {
            addCriterion("`check_item_value` not between", value1, value2, "checkItemValue");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionIsNull() {
            addCriterion("`check_item_description` is null");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionIsNotNull() {
            addCriterion("`check_item_description` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionEqualTo(String value) {
            addCriterion("`check_item_description` =", value, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionNotEqualTo(String value) {
            addCriterion("`check_item_description` <>", value, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionGreaterThan(String value) {
            addCriterion("`check_item_description` >", value, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("`check_item_description` >=", value, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionLessThan(String value) {
            addCriterion("`check_item_description` <", value, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionLessThanOrEqualTo(String value) {
            addCriterion("`check_item_description` <=", value, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionLike(String value) {
            addCriterion("`check_item_description` like", value, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionNotLike(String value) {
            addCriterion("`check_item_description` not like", value, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionIn(List<String> values) {
            addCriterion("`check_item_description` in", values, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionNotIn(List<String> values) {
            addCriterion("`check_item_description` not in", values, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionBetween(String value1, String value2) {
            addCriterion("`check_item_description` between", value1, value2, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemDescriptionNotBetween(String value1, String value2) {
            addCriterion("`check_item_description` not between", value1, value2, "checkItemDescription");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeIsNull() {
            addCriterion("`check_item_type` is null");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeIsNotNull() {
            addCriterion("`check_item_type` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeEqualTo(Integer value) {
            addCriterion("`check_item_type` =", value, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNotEqualTo(Integer value) {
            addCriterion("`check_item_type` <>", value, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeGreaterThan(Integer value) {
            addCriterion("`check_item_type` >", value, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`check_item_type` >=", value, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeLessThan(Integer value) {
            addCriterion("`check_item_type` <", value, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`check_item_type` <=", value, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeIn(List<Integer> values) {
            addCriterion("`check_item_type` in", values, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNotIn(List<Integer> values) {
            addCriterion("`check_item_type` not in", values, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeBetween(Integer value1, Integer value2) {
            addCriterion("`check_item_type` between", value1, value2, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`check_item_type` not between", value1, value2, "checkItemType");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameIsNull() {
            addCriterion("`check_item_type_name` is null");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameIsNotNull() {
            addCriterion("`check_item_type_name` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameEqualTo(String value) {
            addCriterion("`check_item_type_name` =", value, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameNotEqualTo(String value) {
            addCriterion("`check_item_type_name` <>", value, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameGreaterThan(String value) {
            addCriterion("`check_item_type_name` >", value, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`check_item_type_name` >=", value, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameLessThan(String value) {
            addCriterion("`check_item_type_name` <", value, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`check_item_type_name` <=", value, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameLike(String value) {
            addCriterion("`check_item_type_name` like", value, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameNotLike(String value) {
            addCriterion("`check_item_type_name` not like", value, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameIn(List<String> values) {
            addCriterion("`check_item_type_name` in", values, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameNotIn(List<String> values) {
            addCriterion("`check_item_type_name` not in", values, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameBetween(String value1, String value2) {
            addCriterion("`check_item_type_name` between", value1, value2, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckItemTypeNameNotBetween(String value1, String value2) {
            addCriterion("`check_item_type_name` not between", value1, value2, "checkItemTypeName");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("`creator` is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("`creator` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("`creator` =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("`creator` <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("`creator` >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("`creator` >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("`creator` <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("`creator` <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("`creator` like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("`creator` not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("`creator` in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("`creator` not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("`creator` between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("`creator` not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("`updater` is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("`updater` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("`updater` =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("`updater` <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("`updater` >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("`updater` >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("`updater` <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("`updater` <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("`updater` like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("`updater` not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("`updater` in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("`updater` not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("`updater` between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("`updater` not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("`deleteflag` is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("`deleteflag` is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("`deleteflag` =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("`deleteflag` <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("`deleteflag` >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("`deleteflag` >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("`deleteflag` <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("`deleteflag` <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("`deleteflag` in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("`deleteflag` not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("`deleteflag` between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("`deleteflag` not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table check_items
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 09 14:47:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}