package com.jzfq.rms.product.bean;

import java.util.Date;

public class CheckItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.check_item_id
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private Integer checkItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private Integer checkItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.check_item_value
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private String checkItemValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.check_item_description
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private String checkItemDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.check_item_type
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private Integer checkItemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.check_item_type_name
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private String checkItemTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.creator
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.create_time
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.updater
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.update_time
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.deleteflag
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.check_item_id
     *
     * @return the value of check_items.check_item_id
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public Integer getCheckItemId() {
        return checkItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.check_item_id
     *
     * @param checkItemId the value for check_items.check_item_id
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setCheckItemId(Integer checkItemId) {
        this.checkItemId = checkItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.check_items
     *
     * @return the value of check_items.check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public Integer getCheckItems() {
        return checkItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.check_items
     *
     * @param checkItems the value for check_items.check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setCheckItems(Integer checkItems) {
        this.checkItems = checkItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.check_item_value
     *
     * @return the value of check_items.check_item_value
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public String getCheckItemValue() {
        return checkItemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.check_item_value
     *
     * @param checkItemValue the value for check_items.check_item_value
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setCheckItemValue(String checkItemValue) {
        this.checkItemValue = checkItemValue == null ? null : checkItemValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.check_item_description
     *
     * @return the value of check_items.check_item_description
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public String getCheckItemDescription() {
        return checkItemDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.check_item_description
     *
     * @param checkItemDescription the value for check_items.check_item_description
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setCheckItemDescription(String checkItemDescription) {
        this.checkItemDescription = checkItemDescription == null ? null : checkItemDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.check_item_type
     *
     * @return the value of check_items.check_item_type
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public Integer getCheckItemType() {
        return checkItemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.check_item_type
     *
     * @param checkItemType the value for check_items.check_item_type
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setCheckItemType(Integer checkItemType) {
        this.checkItemType = checkItemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.check_item_type_name
     *
     * @return the value of check_items.check_item_type_name
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public String getCheckItemTypeName() {
        return checkItemTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.check_item_type_name
     *
     * @param checkItemTypeName the value for check_items.check_item_type_name
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setCheckItemTypeName(String checkItemTypeName) {
        this.checkItemTypeName = checkItemTypeName == null ? null : checkItemTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.creator
     *
     * @return the value of check_items.creator
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.creator
     *
     * @param creator the value for check_items.creator
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.create_time
     *
     * @return the value of check_items.create_time
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.create_time
     *
     * @param createTime the value for check_items.create_time
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.updater
     *
     * @return the value of check_items.updater
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.updater
     *
     * @param updater the value for check_items.updater
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.update_time
     *
     * @return the value of check_items.update_time
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.update_time
     *
     * @param updateTime the value for check_items.update_time
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.deleteflag
     *
     * @return the value of check_items.deleteflag
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.deleteflag
     *
     * @param deleteflag the value for check_items.deleteflag
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}