package com.jzfq.rms.product.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DecisionSetsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public DecisionSetsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDecisionIdIsNull() {
            addCriterion("`decision_ID` is null");
            return (Criteria) this;
        }

        public Criteria andDecisionIdIsNotNull() {
            addCriterion("`decision_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionIdEqualTo(Integer value) {
            addCriterion("`decision_ID` =", value, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdNotEqualTo(Integer value) {
            addCriterion("`decision_ID` <>", value, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdGreaterThan(Integer value) {
            addCriterion("`decision_ID` >", value, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`decision_ID` >=", value, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdLessThan(Integer value) {
            addCriterion("`decision_ID` <", value, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdLessThanOrEqualTo(Integer value) {
            addCriterion("`decision_ID` <=", value, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdIn(List<Integer> values) {
            addCriterion("`decision_ID` in", values, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdNotIn(List<Integer> values) {
            addCriterion("`decision_ID` not in", values, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdBetween(Integer value1, Integer value2) {
            addCriterion("`decision_ID` between", value1, value2, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`decision_ID` not between", value1, value2, "decisionId");
            return (Criteria) this;
        }

        public Criteria andDecisionNoIsNull() {
            addCriterion("`decision_No` is null");
            return (Criteria) this;
        }

        public Criteria andDecisionNoIsNotNull() {
            addCriterion("`decision_No` is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionNoEqualTo(String value) {
            addCriterion("`decision_No` =", value, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoNotEqualTo(String value) {
            addCriterion("`decision_No` <>", value, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoGreaterThan(String value) {
            addCriterion("`decision_No` >", value, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoGreaterThanOrEqualTo(String value) {
            addCriterion("`decision_No` >=", value, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoLessThan(String value) {
            addCriterion("`decision_No` <", value, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoLessThanOrEqualTo(String value) {
            addCriterion("`decision_No` <=", value, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoLike(String value) {
            addCriterion("`decision_No` like", value, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoNotLike(String value) {
            addCriterion("`decision_No` not like", value, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoIn(List<String> values) {
            addCriterion("`decision_No` in", values, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoNotIn(List<String> values) {
            addCriterion("`decision_No` not in", values, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoBetween(String value1, String value2) {
            addCriterion("`decision_No` between", value1, value2, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andDecisionNoNotBetween(String value1, String value2) {
            addCriterion("`decision_No` not between", value1, value2, "decisionNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdIsNull() {
            addCriterion("`rule_sets_ID` is null");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdIsNotNull() {
            addCriterion("`rule_sets_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdEqualTo(Integer value) {
            addCriterion("`rule_sets_ID` =", value, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdNotEqualTo(Integer value) {
            addCriterion("`rule_sets_ID` <>", value, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdGreaterThan(Integer value) {
            addCriterion("`rule_sets_ID` >", value, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`rule_sets_ID` >=", value, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdLessThan(Integer value) {
            addCriterion("`rule_sets_ID` <", value, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdLessThanOrEqualTo(Integer value) {
            addCriterion("`rule_sets_ID` <=", value, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdIn(List<Integer> values) {
            addCriterion("`rule_sets_ID` in", values, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdNotIn(List<Integer> values) {
            addCriterion("`rule_sets_ID` not in", values, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdBetween(Integer value1, Integer value2) {
            addCriterion("`rule_sets_ID` between", value1, value2, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`rule_sets_ID` not between", value1, value2, "ruleSetsId");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoIsNull() {
            addCriterion("`rule_sets_No` is null");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoIsNotNull() {
            addCriterion("`rule_sets_No` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoEqualTo(String value) {
            addCriterion("`rule_sets_No` =", value, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoNotEqualTo(String value) {
            addCriterion("`rule_sets_No` <>", value, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoGreaterThan(String value) {
            addCriterion("`rule_sets_No` >", value, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoGreaterThanOrEqualTo(String value) {
            addCriterion("`rule_sets_No` >=", value, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoLessThan(String value) {
            addCriterion("`rule_sets_No` <", value, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoLessThanOrEqualTo(String value) {
            addCriterion("`rule_sets_No` <=", value, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoLike(String value) {
            addCriterion("`rule_sets_No` like", value, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoNotLike(String value) {
            addCriterion("`rule_sets_No` not like", value, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoIn(List<String> values) {
            addCriterion("`rule_sets_No` in", values, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoNotIn(List<String> values) {
            addCriterion("`rule_sets_No` not in", values, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoBetween(String value1, String value2) {
            addCriterion("`rule_sets_No` between", value1, value2, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andRuleSetsNoNotBetween(String value1, String value2) {
            addCriterion("`rule_sets_No` not between", value1, value2, "ruleSetsNo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_Time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_Time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_Time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_Time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_Time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_Time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_Time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_Time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_Time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_Time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_Time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_Time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("`creator` is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("`creator` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("`creator` =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("`creator` <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("`creator` >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("`creator` >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("`creator` <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("`creator` <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("`creator` like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("`creator` not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("`creator` in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("`creator` not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("`creator` between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("`creator` not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_Time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_Time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_Time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_Time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_Time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_Time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_Time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_Time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_Time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_Time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_Time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_Time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("`updater` is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("`updater` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("`updater` =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("`updater` <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("`updater` >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("`updater` >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("`updater` <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("`updater` <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("`updater` like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("`updater` not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("`updater` in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("`updater` not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("`updater` between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("`updater` not between", value1, value2, "updater");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table decision_sets
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 09 16:37:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table decision_sets
     *
     * @mbg.generated Thu Nov 09 16:37:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}