package com.jzfq.rms.product.bean;

import com.jzfq.rms.product.common.Page;

import java.util.Date;

public class Dictionary extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.id
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.type
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.rms_key
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private String rms_key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.rms_value
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private String rms_value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.description
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.create_user
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private String create_user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.create_time
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.update_user
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private String update_user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.update_time
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private Date update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.del_flag
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    private Byte del_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.id
     *
     * @return the value of dictionary.id
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.id
     *
     * @param id the value for dictionary.id
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.type
     *
     * @return the value of dictionary.type
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.type
     *
     * @param type the value for dictionary.type
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.rms_key
     *
     * @return the value of dictionary.rms_key
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public String getRms_key() {
        return rms_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.rms_key
     *
     * @param rms_key the value for dictionary.rms_key
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setRms_key(String rms_key) {
        this.rms_key = rms_key == null ? null : rms_key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.rms_value
     *
     * @return the value of dictionary.rms_value
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public String getRms_value() {
        return rms_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.rms_value
     *
     * @param rms_value the value for dictionary.rms_value
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setRms_value(String rms_value) {
        this.rms_value = rms_value == null ? null : rms_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.description
     *
     * @return the value of dictionary.description
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.description
     *
     * @param description the value for dictionary.description
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.create_user
     *
     * @return the value of dictionary.create_user
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public String getCreate_user() {
        return create_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.create_user
     *
     * @param create_user the value for dictionary.create_user
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setCreate_user(String create_user) {
        this.create_user = create_user == null ? null : create_user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.create_time
     *
     * @return the value of dictionary.create_time
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public Date getCreate_time() {
        return create_time == null ? create_time : (Date)create_time.clone();

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.create_time
     *
     * @param create_time the value for dictionary.create_time
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time == null ? create_time : (Date)create_time.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.update_user
     *
     * @return the value of dictionary.update_user
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public String getUpdate_user() {
        return update_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.update_user
     *
     * @param update_user the value for dictionary.update_user
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setUpdate_user(String update_user) {
        this.update_user = update_user == null ? null : update_user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.update_time
     *
     * @return the value of dictionary.update_time
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public Date getUpdate_time() {
        return update_time == null ? update_time : (Date)update_time.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.update_time
     *
     * @param update_time the value for dictionary.update_time
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time == null ? update_time : (Date)update_time.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.del_flag
     *
     * @return the value of dictionary.del_flag
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public Byte getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.del_flag
     *
     * @param del_flag the value for dictionary.del_flag
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setDel_flag(Byte del_flag) {
        this.del_flag = del_flag;
    }
}