package com.jzfq.rms.product.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DictionaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public DictionaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("`type` like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("`type` not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andRms_keyIsNull() {
            addCriterion("`rms_key` is null");
            return (Criteria) this;
        }

        public Criteria andRms_keyIsNotNull() {
            addCriterion("`rms_key` is not null");
            return (Criteria) this;
        }

        public Criteria andRms_keyEqualTo(String value) {
            addCriterion("`rms_key` =", value, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyNotEqualTo(String value) {
            addCriterion("`rms_key` <>", value, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyGreaterThan(String value) {
            addCriterion("`rms_key` >", value, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyGreaterThanOrEqualTo(String value) {
            addCriterion("`rms_key` >=", value, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyLessThan(String value) {
            addCriterion("`rms_key` <", value, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyLessThanOrEqualTo(String value) {
            addCriterion("`rms_key` <=", value, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyLike(String value) {
            addCriterion("`rms_key` like", value, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyNotLike(String value) {
            addCriterion("`rms_key` not like", value, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyIn(List<String> values) {
            addCriterion("`rms_key` in", values, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyNotIn(List<String> values) {
            addCriterion("`rms_key` not in", values, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyBetween(String value1, String value2) {
            addCriterion("`rms_key` between", value1, value2, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_keyNotBetween(String value1, String value2) {
            addCriterion("`rms_key` not between", value1, value2, "rms_key");
            return (Criteria) this;
        }

        public Criteria andRms_valueIsNull() {
            addCriterion("`rms_value` is null");
            return (Criteria) this;
        }

        public Criteria andRms_valueIsNotNull() {
            addCriterion("`rms_value` is not null");
            return (Criteria) this;
        }

        public Criteria andRms_valueEqualTo(String value) {
            addCriterion("`rms_value` =", value, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueNotEqualTo(String value) {
            addCriterion("`rms_value` <>", value, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueGreaterThan(String value) {
            addCriterion("`rms_value` >", value, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueGreaterThanOrEqualTo(String value) {
            addCriterion("`rms_value` >=", value, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueLessThan(String value) {
            addCriterion("`rms_value` <", value, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueLessThanOrEqualTo(String value) {
            addCriterion("`rms_value` <=", value, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueLike(String value) {
            addCriterion("`rms_value` like", value, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueNotLike(String value) {
            addCriterion("`rms_value` not like", value, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueIn(List<String> values) {
            addCriterion("`rms_value` in", values, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueNotIn(List<String> values) {
            addCriterion("`rms_value` not in", values, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueBetween(String value1, String value2) {
            addCriterion("`rms_value` between", value1, value2, "rms_value");
            return (Criteria) this;
        }

        public Criteria andRms_valueNotBetween(String value1, String value2) {
            addCriterion("`rms_value` not between", value1, value2, "rms_value");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("`description` is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("`description` is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("`description` =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("`description` <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("`description` >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("`description` >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("`description` <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("`description` <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("`description` like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("`description` not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("`description` in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("`description` not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("`description` between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("`description` not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreate_userIsNull() {
            addCriterion("`create_user` is null");
            return (Criteria) this;
        }

        public Criteria andCreate_userIsNotNull() {
            addCriterion("`create_user` is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_userEqualTo(String value) {
            addCriterion("`create_user` =", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userNotEqualTo(String value) {
            addCriterion("`create_user` <>", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userGreaterThan(String value) {
            addCriterion("`create_user` >", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userGreaterThanOrEqualTo(String value) {
            addCriterion("`create_user` >=", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userLessThan(String value) {
            addCriterion("`create_user` <", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userLessThanOrEqualTo(String value) {
            addCriterion("`create_user` <=", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userLike(String value) {
            addCriterion("`create_user` like", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userNotLike(String value) {
            addCriterion("`create_user` not like", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userIn(List<String> values) {
            addCriterion("`create_user` in", values, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userNotIn(List<String> values) {
            addCriterion("`create_user` not in", values, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userBetween(String value1, String value2) {
            addCriterion("`create_user` between", value1, value2, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userNotBetween(String value1, String value2) {
            addCriterion("`create_user` not between", value1, value2, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("`create_time` <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_userIsNull() {
            addCriterion("`update_user` is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_userIsNotNull() {
            addCriterion("`update_user` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_userEqualTo(String value) {
            addCriterion("`update_user` =", value, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userNotEqualTo(String value) {
            addCriterion("`update_user` <>", value, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userGreaterThan(String value) {
            addCriterion("`update_user` >", value, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userGreaterThanOrEqualTo(String value) {
            addCriterion("`update_user` >=", value, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userLessThan(String value) {
            addCriterion("`update_user` <", value, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userLessThanOrEqualTo(String value) {
            addCriterion("`update_user` <=", value, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userLike(String value) {
            addCriterion("`update_user` like", value, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userNotLike(String value) {
            addCriterion("`update_user` not like", value, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userIn(List<String> values) {
            addCriterion("`update_user` in", values, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userNotIn(List<String> values) {
            addCriterion("`update_user` not in", values, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userBetween(String value1, String value2) {
            addCriterion("`update_user` between", value1, value2, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_userNotBetween(String value1, String value2) {
            addCriterion("`update_user` not between", value1, value2, "update_user");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("`update_time` <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andDel_flagIsNull() {
            addCriterion("`del_flag` is null");
            return (Criteria) this;
        }

        public Criteria andDel_flagIsNotNull() {
            addCriterion("`del_flag` is not null");
            return (Criteria) this;
        }

        public Criteria andDel_flagEqualTo(Byte value) {
            addCriterion("`del_flag` =", value, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagNotEqualTo(Byte value) {
            addCriterion("`del_flag` <>", value, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagGreaterThan(Byte value) {
            addCriterion("`del_flag` >", value, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagGreaterThanOrEqualTo(Byte value) {
            addCriterion("`del_flag` >=", value, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagLessThan(Byte value) {
            addCriterion("`del_flag` <", value, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagLessThanOrEqualTo(Byte value) {
            addCriterion("`del_flag` <=", value, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagIn(List<Byte> values) {
            addCriterion("`del_flag` in", values, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagNotIn(List<Byte> values) {
            addCriterion("`del_flag` not in", values, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagBetween(Byte value1, Byte value2) {
            addCriterion("`del_flag` between", value1, value2, "del_flag");
            return (Criteria) this;
        }

        public Criteria andDel_flagNotBetween(Byte value1, Byte value2) {
            addCriterion("`del_flag` not between", value1, value2, "del_flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dictionary
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 17 15:23:41 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}