package com.jzfq.rms.product.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public ProductInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("`product_id` is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("`product_id` is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("`product_id` =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("`product_id` <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("`product_id` >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`product_id` >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("`product_id` <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("`product_id` <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("`product_id` in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("`product_id` not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("`product_id` between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`product_id` not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoIsNull() {
            addCriterion("`product_order_No` is null");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoIsNotNull() {
            addCriterion("`product_order_No` is not null");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoEqualTo(String value) {
            addCriterion("`product_order_No` =", value, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoNotEqualTo(String value) {
            addCriterion("`product_order_No` <>", value, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoGreaterThan(String value) {
            addCriterion("`product_order_No` >", value, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("`product_order_No` >=", value, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoLessThan(String value) {
            addCriterion("`product_order_No` <", value, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoLessThanOrEqualTo(String value) {
            addCriterion("`product_order_No` <=", value, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoLike(String value) {
            addCriterion("`product_order_No` like", value, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoNotLike(String value) {
            addCriterion("`product_order_No` not like", value, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoIn(List<String> values) {
            addCriterion("`product_order_No` in", values, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoNotIn(List<String> values) {
            addCriterion("`product_order_No` not in", values, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoBetween(String value1, String value2) {
            addCriterion("`product_order_No` between", value1, value2, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andProductOrderNoNotBetween(String value1, String value2) {
            addCriterion("`product_order_No` not between", value1, value2, "productOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("`channel_id` is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("`channel_id` is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(String value) {
            addCriterion("`channel_id` =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(String value) {
            addCriterion("`channel_id` <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(String value) {
            addCriterion("`channel_id` >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("`channel_id` >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(String value) {
            addCriterion("`channel_id` <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(String value) {
            addCriterion("`channel_id` <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLike(String value) {
            addCriterion("`channel_id` like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotLike(String value) {
            addCriterion("`channel_id` not like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<String> values) {
            addCriterion("`channel_id` in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<String> values) {
            addCriterion("`channel_id` not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(String value1, String value2) {
            addCriterion("`channel_id` between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(String value1, String value2) {
            addCriterion("`channel_id` not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("`product_name` is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("`product_name` is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("`product_name` =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("`product_name` <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("`product_name` >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("`product_name` >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("`product_name` <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("`product_name` <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("`product_name` like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("`product_name` not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("`product_name` in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("`product_name` not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("`product_name` between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("`product_name` not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("`channel_name` is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("`channel_name` is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("`channel_name` =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("`channel_name` <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("`channel_name` >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("`channel_name` >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("`channel_name` <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("`channel_name` <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("`channel_name` like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("`channel_name` not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("`channel_name` in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("`channel_name` not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("`channel_name` between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("`channel_name` not between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdIsNull() {
            addCriterion("`financial_product_id` is null");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdIsNotNull() {
            addCriterion("`financial_product_id` is not null");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdEqualTo(String value) {
            addCriterion("`financial_product_id` =", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotEqualTo(String value) {
            addCriterion("`financial_product_id` <>", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdGreaterThan(String value) {
            addCriterion("`financial_product_id` >", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("`financial_product_id` >=", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdLessThan(String value) {
            addCriterion("`financial_product_id` <", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdLessThanOrEqualTo(String value) {
            addCriterion("`financial_product_id` <=", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdLike(String value) {
            addCriterion("`financial_product_id` like", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotLike(String value) {
            addCriterion("`financial_product_id` not like", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdIn(List<String> values) {
            addCriterion("`financial_product_id` in", values, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotIn(List<String> values) {
            addCriterion("`financial_product_id` not in", values, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdBetween(String value1, String value2) {
            addCriterion("`financial_product_id` between", value1, value2, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotBetween(String value1, String value2) {
            addCriterion("`financial_product_id` not between", value1, value2, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameIsNull() {
            addCriterion("`financial_product_name` is null");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameIsNotNull() {
            addCriterion("`financial_product_name` is not null");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameEqualTo(String value) {
            addCriterion("`financial_product_name` =", value, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameNotEqualTo(String value) {
            addCriterion("`financial_product_name` <>", value, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameGreaterThan(String value) {
            addCriterion("`financial_product_name` >", value, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("`financial_product_name` >=", value, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameLessThan(String value) {
            addCriterion("`financial_product_name` <", value, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameLessThanOrEqualTo(String value) {
            addCriterion("`financial_product_name` <=", value, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameLike(String value) {
            addCriterion("`financial_product_name` like", value, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameNotLike(String value) {
            addCriterion("`financial_product_name` not like", value, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameIn(List<String> values) {
            addCriterion("`financial_product_name` in", values, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameNotIn(List<String> values) {
            addCriterion("`financial_product_name` not in", values, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameBetween(String value1, String value2) {
            addCriterion("`financial_product_name` between", value1, value2, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andFinancialProductNameNotBetween(String value1, String value2) {
            addCriterion("`financial_product_name` not between", value1, value2, "financialProductName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeIsNull() {
            addCriterion("`custom_type` is null");
            return (Criteria) this;
        }

        public Criteria andCustomTypeIsNotNull() {
            addCriterion("`custom_type` is not null");
            return (Criteria) this;
        }

        public Criteria andCustomTypeEqualTo(Integer value) {
            addCriterion("`custom_type` =", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNotEqualTo(Integer value) {
            addCriterion("`custom_type` <>", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeGreaterThan(Integer value) {
            addCriterion("`custom_type` >", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`custom_type` >=", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeLessThan(Integer value) {
            addCriterion("`custom_type` <", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`custom_type` <=", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeIn(List<Integer> values) {
            addCriterion("`custom_type` in", values, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNotIn(List<Integer> values) {
            addCriterion("`custom_type` not in", values, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeBetween(Integer value1, Integer value2) {
            addCriterion("`custom_type` between", value1, value2, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`custom_type` not between", value1, value2, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameIsNull() {
            addCriterion("`custom_type_name` is null");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameIsNotNull() {
            addCriterion("`custom_type_name` is not null");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameEqualTo(String value) {
            addCriterion("`custom_type_name` =", value, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameNotEqualTo(String value) {
            addCriterion("`custom_type_name` <>", value, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameGreaterThan(String value) {
            addCriterion("`custom_type_name` >", value, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`custom_type_name` >=", value, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameLessThan(String value) {
            addCriterion("`custom_type_name` <", value, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`custom_type_name` <=", value, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameLike(String value) {
            addCriterion("`custom_type_name` like", value, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameNotLike(String value) {
            addCriterion("`custom_type_name` not like", value, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameIn(List<String> values) {
            addCriterion("`custom_type_name` in", values, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameNotIn(List<String> values) {
            addCriterion("`custom_type_name` not in", values, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameBetween(String value1, String value2) {
            addCriterion("`custom_type_name` between", value1, value2, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNameNotBetween(String value1, String value2) {
            addCriterion("`custom_type_name` not between", value1, value2, "customTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNull() {
            addCriterion("`operation_type` is null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNotNull() {
            addCriterion("`operation_type` is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeEqualTo(Integer value) {
            addCriterion("`operation_type` =", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotEqualTo(Integer value) {
            addCriterion("`operation_type` <>", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeGreaterThan(Integer value) {
            addCriterion("`operation_type` >", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`operation_type` >=", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLessThan(Integer value) {
            addCriterion("`operation_type` <", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`operation_type` <=", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIn(List<Integer> values) {
            addCriterion("`operation_type` in", values, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotIn(List<Integer> values) {
            addCriterion("`operation_type` not in", values, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeBetween(Integer value1, Integer value2) {
            addCriterion("`operation_type` between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`operation_type` not between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameIsNull() {
            addCriterion("`operation_type_name` is null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameIsNotNull() {
            addCriterion("`operation_type_name` is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameEqualTo(String value) {
            addCriterion("`operation_type_name` =", value, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameNotEqualTo(String value) {
            addCriterion("`operation_type_name` <>", value, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameGreaterThan(String value) {
            addCriterion("`operation_type_name` >", value, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`operation_type_name` >=", value, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameLessThan(String value) {
            addCriterion("`operation_type_name` <", value, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`operation_type_name` <=", value, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameLike(String value) {
            addCriterion("`operation_type_name` like", value, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameNotLike(String value) {
            addCriterion("`operation_type_name` not like", value, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameIn(List<String> values) {
            addCriterion("`operation_type_name` in", values, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameNotIn(List<String> values) {
            addCriterion("`operation_type_name` not in", values, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameBetween(String value1, String value2) {
            addCriterion("`operation_type_name` between", value1, value2, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNameNotBetween(String value1, String value2) {
            addCriterion("`operation_type_name` not between", value1, value2, "operationTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeIsNull() {
            addCriterion("`operation_sub_type` is null");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeIsNotNull() {
            addCriterion("`operation_sub_type` is not null");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeEqualTo(Integer value) {
            addCriterion("`operation_sub_type` =", value, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNotEqualTo(Integer value) {
            addCriterion("`operation_sub_type` <>", value, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeGreaterThan(Integer value) {
            addCriterion("`operation_sub_type` >", value, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`operation_sub_type` >=", value, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeLessThan(Integer value) {
            addCriterion("`operation_sub_type` <", value, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`operation_sub_type` <=", value, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeIn(List<Integer> values) {
            addCriterion("`operation_sub_type` in", values, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNotIn(List<Integer> values) {
            addCriterion("`operation_sub_type` not in", values, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeBetween(Integer value1, Integer value2) {
            addCriterion("`operation_sub_type` between", value1, value2, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`operation_sub_type` not between", value1, value2, "operationSubType");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameIsNull() {
            addCriterion("`operation_sub_type_name` is null");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameIsNotNull() {
            addCriterion("`operation_sub_type_name` is not null");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameEqualTo(String value) {
            addCriterion("`operation_sub_type_name` =", value, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameNotEqualTo(String value) {
            addCriterion("`operation_sub_type_name` <>", value, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameGreaterThan(String value) {
            addCriterion("`operation_sub_type_name` >", value, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`operation_sub_type_name` >=", value, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameLessThan(String value) {
            addCriterion("`operation_sub_type_name` <", value, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`operation_sub_type_name` <=", value, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameLike(String value) {
            addCriterion("`operation_sub_type_name` like", value, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameNotLike(String value) {
            addCriterion("`operation_sub_type_name` not like", value, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameIn(List<String> values) {
            addCriterion("`operation_sub_type_name` in", values, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameNotIn(List<String> values) {
            addCriterion("`operation_sub_type_name` not in", values, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameBetween(String value1, String value2) {
            addCriterion("`operation_sub_type_name` between", value1, value2, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andOperationSubTypeNameNotBetween(String value1, String value2) {
            addCriterion("`operation_sub_type_name` not between", value1, value2, "operationSubTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeIsNull() {
            addCriterion("`merchant_type` is null");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeIsNotNull() {
            addCriterion("`merchant_type` is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeEqualTo(Integer value) {
            addCriterion("`merchant_type` =", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNotEqualTo(Integer value) {
            addCriterion("`merchant_type` <>", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeGreaterThan(Integer value) {
            addCriterion("`merchant_type` >", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`merchant_type` >=", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeLessThan(Integer value) {
            addCriterion("`merchant_type` <", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`merchant_type` <=", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeIn(List<Integer> values) {
            addCriterion("`merchant_type` in", values, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNotIn(List<Integer> values) {
            addCriterion("`merchant_type` not in", values, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeBetween(Integer value1, Integer value2) {
            addCriterion("`merchant_type` between", value1, value2, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`merchant_type` not between", value1, value2, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameIsNull() {
            addCriterion("`merchant_type_name` is null");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameIsNotNull() {
            addCriterion("`merchant_type_name` is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameEqualTo(String value) {
            addCriterion("`merchant_type_name` =", value, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameNotEqualTo(String value) {
            addCriterion("`merchant_type_name` <>", value, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameGreaterThan(String value) {
            addCriterion("`merchant_type_name` >", value, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`merchant_type_name` >=", value, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameLessThan(String value) {
            addCriterion("`merchant_type_name` <", value, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`merchant_type_name` <=", value, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameLike(String value) {
            addCriterion("`merchant_type_name` like", value, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameNotLike(String value) {
            addCriterion("`merchant_type_name` not like", value, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameIn(List<String> values) {
            addCriterion("`merchant_type_name` in", values, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameNotIn(List<String> values) {
            addCriterion("`merchant_type_name` not in", values, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameBetween(String value1, String value2) {
            addCriterion("`merchant_type_name` between", value1, value2, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNameNotBetween(String value1, String value2) {
            addCriterion("`merchant_type_name` not between", value1, value2, "merchantTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNull() {
            addCriterion("`client_type` is null");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNotNull() {
            addCriterion("`client_type` is not null");
            return (Criteria) this;
        }

        public Criteria andClientTypeEqualTo(Integer value) {
            addCriterion("`client_type` =", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotEqualTo(Integer value) {
            addCriterion("`client_type` <>", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThan(Integer value) {
            addCriterion("`client_type` >", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`client_type` >=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThan(Integer value) {
            addCriterion("`client_type` <", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`client_type` <=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeIn(List<Integer> values) {
            addCriterion("`client_type` in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotIn(List<Integer> values) {
            addCriterion("`client_type` not in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeBetween(Integer value1, Integer value2) {
            addCriterion("`client_type` between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`client_type` not between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameIsNull() {
            addCriterion("`client_type_name` is null");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameIsNotNull() {
            addCriterion("`client_type_name` is not null");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameEqualTo(String value) {
            addCriterion("`client_type_name` =", value, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameNotEqualTo(String value) {
            addCriterion("`client_type_name` <>", value, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameGreaterThan(String value) {
            addCriterion("`client_type_name` >", value, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`client_type_name` >=", value, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameLessThan(String value) {
            addCriterion("`client_type_name` <", value, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`client_type_name` <=", value, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameLike(String value) {
            addCriterion("`client_type_name` like", value, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameNotLike(String value) {
            addCriterion("`client_type_name` not like", value, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameIn(List<String> values) {
            addCriterion("`client_type_name` in", values, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameNotIn(List<String> values) {
            addCriterion("`client_type_name` not in", values, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameBetween(String value1, String value2) {
            addCriterion("`client_type_name` between", value1, value2, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andClientTypeNameNotBetween(String value1, String value2) {
            addCriterion("`client_type_name` not between", value1, value2, "clientTypeName");
            return (Criteria) this;
        }

        public Criteria andMinPeriodIsNull() {
            addCriterion("`min_period` is null");
            return (Criteria) this;
        }

        public Criteria andMinPeriodIsNotNull() {
            addCriterion("`min_period` is not null");
            return (Criteria) this;
        }

        public Criteria andMinPeriodEqualTo(Integer value) {
            addCriterion("`min_period` =", value, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodNotEqualTo(Integer value) {
            addCriterion("`min_period` <>", value, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodGreaterThan(Integer value) {
            addCriterion("`min_period` >", value, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("`min_period` >=", value, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodLessThan(Integer value) {
            addCriterion("`min_period` <", value, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("`min_period` <=", value, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodIn(List<Integer> values) {
            addCriterion("`min_period` in", values, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodNotIn(List<Integer> values) {
            addCriterion("`min_period` not in", values, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodBetween(Integer value1, Integer value2) {
            addCriterion("`min_period` between", value1, value2, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMinPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("`min_period` not between", value1, value2, "minPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodIsNull() {
            addCriterion("`max_period` is null");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodIsNotNull() {
            addCriterion("`max_period` is not null");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodEqualTo(Integer value) {
            addCriterion("`max_period` =", value, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodNotEqualTo(Integer value) {
            addCriterion("`max_period` <>", value, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodGreaterThan(Integer value) {
            addCriterion("`max_period` >", value, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("`max_period` >=", value, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodLessThan(Integer value) {
            addCriterion("`max_period` <", value, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("`max_period` <=", value, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodIn(List<Integer> values) {
            addCriterion("`max_period` in", values, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodNotIn(List<Integer> values) {
            addCriterion("`max_period` not in", values, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodBetween(Integer value1, Integer value2) {
            addCriterion("`max_period` between", value1, value2, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("`max_period` not between", value1, value2, "maxPeriod");
            return (Criteria) this;
        }

        public Criteria andMinAmountIsNull() {
            addCriterion("`min_amount` is null");
            return (Criteria) this;
        }

        public Criteria andMinAmountIsNotNull() {
            addCriterion("`min_amount` is not null");
            return (Criteria) this;
        }

        public Criteria andMinAmountEqualTo(BigDecimal value) {
            addCriterion("`min_amount` =", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotEqualTo(BigDecimal value) {
            addCriterion("`min_amount` <>", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountGreaterThan(BigDecimal value) {
            addCriterion("`min_amount` >", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`min_amount` >=", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountLessThan(BigDecimal value) {
            addCriterion("`min_amount` <", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`min_amount` <=", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountIn(List<BigDecimal> values) {
            addCriterion("`min_amount` in", values, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotIn(List<BigDecimal> values) {
            addCriterion("`min_amount` not in", values, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`min_amount` between", value1, value2, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`min_amount` not between", value1, value2, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountIsNull() {
            addCriterion("`max_amount` is null");
            return (Criteria) this;
        }

        public Criteria andMaxAmountIsNotNull() {
            addCriterion("`max_amount` is not null");
            return (Criteria) this;
        }

        public Criteria andMaxAmountEqualTo(BigDecimal value) {
            addCriterion("`max_amount` =", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountNotEqualTo(BigDecimal value) {
            addCriterion("`max_amount` <>", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountGreaterThan(BigDecimal value) {
            addCriterion("`max_amount` >", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`max_amount` >=", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountLessThan(BigDecimal value) {
            addCriterion("`max_amount` <", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`max_amount` <=", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountIn(List<BigDecimal> values) {
            addCriterion("`max_amount` in", values, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountNotIn(List<BigDecimal> values) {
            addCriterion("`max_amount` not in", values, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`max_amount` between", value1, value2, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`max_amount` not between", value1, value2, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("`creator` is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("`creator` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("`creator` =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("`creator` <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("`creator` >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("`creator` >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("`creator` <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("`creator` <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("`creator` like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("`creator` not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("`creator` in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("`creator` not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("`creator` between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("`creator` not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("`updater` is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("`updater` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("`updater` =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("`updater` <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("`updater` >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("`updater` >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("`updater` <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("`updater` <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("`updater` like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("`updater` not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("`updater` in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("`updater` not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("`updater` between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("`updater` not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("`deleteflag` is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("`deleteflag` is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("`deleteflag` =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("`deleteflag` <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("`deleteflag` >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("`deleteflag` >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("`deleteflag` <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("`deleteflag` <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("`deleteflag` in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("`deleteflag` not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("`deleteflag` between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("`deleteflag` not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 16 14:12:04 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}