package com.jzfq.rms.product.bean;

import com.alibaba.fastjson.annotation.JSONField;
import com.jzfq.rms.product.common.Page;
import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;
import java.math.BigDecimal;
import java.util.Date;


/**
 * 订单分类实体
 * @author 大连桔子分期科技有限公司
 * @date 2018年1月25日 16:04:55
 */
public class ProductInfo extends Page{
    /**
     * 产品ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private Integer productId;

    /**
     * 订单策略编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_order_No
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @Pattern(regexp = "^[\\u4E00-\\u9FA5A-Za-z0-9_]+$", message = "订单策略编号不符合规范！")
    private String productOrderNo;

    /**
     * 渠道ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.channel_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @NotBlank(message = "渠道ID不能为空！")
    @Pattern(regexp = "^[\\u4E00-\\u9FA5A-Za-z0-9_]+$", message = "渠道ID不符合规范！")
    private String channelId;

    /**
     * 订单策略名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @NotBlank(message = "订单策略名称不能为空！")
    private String productName;

    /**
     * 渠道名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.channel_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String channelName;

    /**
     * 金融产品ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.financial_product_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @NotBlank(message = "金融产品不能为空！")
    @Pattern(regexp = "^[0-9]\\d*$", message = "金融产品ID必须为数字！")
    private String financialProductId;

    /**
     * 金融产品名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.financial_product_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String financialProductName;

    /**
     * 客户群体类型
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.custom_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @NotBlank(message = "客户群体不能为空！")
    @Pattern(regexp = "^[0-9]\\d*$", message = "客户群体类型必须为数字！")
    private String customType;

    /**
     * 客户群体类型名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.custom_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String customTypeName;

    /**
     * 操作类型
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.operation_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @NotBlank(message = "操作类型不能为空！")
    @Pattern(regexp = "^[0-9]\\d*$", message = "操作类型必须为数字！")
    private String operationType;

    /**
     * 操作类型名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.operation_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String operationTypeName;

    /**
     * 操作子类型（提额类型）
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.operation_sub_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @NotBlank(message = "提额类型不能为空！")
    @Pattern(regexp = "^[0-9]\\d*$", message = "提额类型必须为数字！")
    private String operationSubType;

    /**
     * 操作子类型名称（提额类型）
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.operation_sub_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String operationSubTypeName;

    /**
     * 商户类型
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.merchant_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @NotBlank(message = "商户类型不能为空！")
    @Pattern(regexp = "^[0-9]\\d*$", message = "商户类型必须为数字！")
    private String merchantType;

    /**
     * 商户类型名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.merchant_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String merchantTypeName;

    /**
     * 客户端类型（设备类型）
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.client_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @NotBlank(message = "设备类型不能为空！")
    @Pattern(regexp = "^[0-9]\\d*$", message = "设备类型必须为数字！")
    private String clientType;

    /**
     * 客户端类型名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.client_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String clientTypeName;

    /**
     * 最小期数
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.min_period
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @Min(value = 0, message = "最小期数必须为正整数！")
    private Integer minPeriod;

    /**
     * 最大期数
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.max_period
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @Min(value = 0, message = "最大期数必须为正整数！")
    private Integer maxPeriod;

    /**
     * 最小金额(元)
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.min_amount
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @DecimalMin(value = "0",message = "最小金额格式不符！")
    private BigDecimal minAmount;

    /**
     * 最大金额(元)
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.max_amount
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @DecimalMin(value = "0",message = "最大金额 格式不符！")
    private BigDecimal maxAmount;

    /**
     * 备注
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.remark
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String remark;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * 创建人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.creator
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String creator;

    /**
     * 更新时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * 更新人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.updater
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String updater;

    /**
     * 删除flag（0：可用、1：已删除）
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.deleteflag
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private Integer deleteflag;

    /**
     * 额度策略ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.tacticsEDID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String tacticsedid;

    /**
     * 准入策略ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.tacticsZRID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String tacticszrid;

    /**
     * 风控策略ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.tacticsFKID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    private String tacticsfkid;

    /**
     * 客群策略ID
     */
    private String tacticsKQID;

    /**
     * 队列编号
     */
    private int queueNum;

    /**
     * 优先级
     */
    private int priorityLevel;

    /**
     * 商品品类Key
     */
    private int commodityType;

    /**
     * 商户渠道Key
     */
    private int commodityChannel;

    /**
     * 执行顺序
     */
    private int executeOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_order_No
     *
     * @return the value of product_info.product_order_No
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getProductOrderNo() {
        return productOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_order_No
     *
     * @param productOrderNo the value for product_info.product_order_No
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setProductOrderNo(String productOrderNo) {
        this.productOrderNo = productOrderNo == null ? null : productOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.channel_id
     *
     * @return the value of product_info.channel_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.channel_id
     *
     * @param channelId the value for product_info.channel_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.channel_name
     *
     * @return the value of product_info.channel_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.channel_name
     *
     * @param channelName the value for product_info.channel_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.financial_product_id
     *
     * @return the value of product_info.financial_product_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getFinancialProductId() {
        return financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.financial_product_id
     *
     * @param financialProductId the value for product_info.financial_product_id
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setFinancialProductId(String financialProductId) {
        this.financialProductId = financialProductId == null ? null : financialProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.financial_product_name
     *
     * @return the value of product_info.financial_product_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getFinancialProductName() {
        return financialProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.financial_product_name
     *
     * @param financialProductName the value for product_info.financial_product_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setFinancialProductName(String financialProductName) {
        this.financialProductName = financialProductName == null ? null : financialProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.custom_type
     *
     * @return the value of product_info.custom_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getCustomType() {
        return customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.custom_type
     *
     * @param customType the value for product_info.custom_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setCustomType(String customType) {
        this.customType = customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.custom_type_name
     *
     * @return the value of product_info.custom_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getCustomTypeName() {
        return customTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.custom_type_name
     *
     * @param customTypeName the value for product_info.custom_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setCustomTypeName(String customTypeName) {
        this.customTypeName = customTypeName == null ? null : customTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.operation_type
     *
     * @return the value of product_info.operation_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.operation_type
     *
     * @param operationType the value for product_info.operation_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.operation_type_name
     *
     * @return the value of product_info.operation_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getOperationTypeName() {
        return operationTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.operation_type_name
     *
     * @param operationTypeName the value for product_info.operation_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setOperationTypeName(String operationTypeName) {
        this.operationTypeName = operationTypeName == null ? null : operationTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.operation_sub_type
     *
     * @return the value of product_info.operation_sub_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getOperationSubType() {
        return operationSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.operation_sub_type
     *
     * @param operationSubType the value for product_info.operation_sub_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setOperationSubType(String operationSubType) {
        this.operationSubType = operationSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.operation_sub_type_name
     *
     * @return the value of product_info.operation_sub_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getOperationSubTypeName() {
        return operationSubTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.operation_sub_type_name
     *
     * @param operationSubTypeName the value for product_info.operation_sub_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setOperationSubTypeName(String operationSubTypeName) {
        this.operationSubTypeName = operationSubTypeName == null ? null : operationSubTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.merchant_type
     *
     * @return the value of product_info.merchant_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getMerchantType() {
        return merchantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.merchant_type
     *
     * @param merchantType the value for product_info.merchant_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setMerchantType(String merchantType) {
        this.merchantType = merchantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.merchant_type_name
     *
     * @return the value of product_info.merchant_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getMerchantTypeName() {
        return merchantTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.merchant_type_name
     *
     * @param merchantTypeName the value for product_info.merchant_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setMerchantTypeName(String merchantTypeName) {
        this.merchantTypeName = merchantTypeName == null ? null : merchantTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.client_type
     *
     * @return the value of product_info.client_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.client_type
     *
     * @param clientType the value for product_info.client_type
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.client_type_name
     *
     * @return the value of product_info.client_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getClientTypeName() {
        return clientTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.client_type_name
     *
     * @param clientTypeName the value for product_info.client_type_name
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setClientTypeName(String clientTypeName) {
        this.clientTypeName = clientTypeName == null ? null : clientTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.min_period
     *
     * @return the value of product_info.min_period
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public Integer getMinPeriod() {
        return minPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.min_period
     *
     * @param minPeriod the value for product_info.min_period
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setMinPeriod(Integer minPeriod) {
        this.minPeriod = minPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.max_period
     *
     * @return the value of product_info.max_period
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public Integer getMaxPeriod() {
        return maxPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.max_period
     *
     * @param maxPeriod the value for product_info.max_period
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setMaxPeriod(Integer maxPeriod) {
        this.maxPeriod = maxPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.min_amount
     *
     * @return the value of product_info.min_amount
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public BigDecimal getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.min_amount
     *
     * @param minAmount the value for product_info.min_amount
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setMinAmount(BigDecimal minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.max_amount
     *
     * @return the value of product_info.max_amount
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public BigDecimal getMaxAmount() {
        return maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.max_amount
     *
     * @param maxAmount the value for product_info.max_amount
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setMaxAmount(BigDecimal maxAmount) {
        this.maxAmount = maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.remark
     *
     * @return the value of product_info.remark
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.remark
     *
     * @param remark the value for product_info.remark
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime == null ? createTime : (Date) createTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.creator
     *
     * @return the value of product_info.creator
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.creator
     *
     * @param creator the value for product_info.creator
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.update_time
     *
     * @return the value of product_info.update_time
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.update_time
     *
     * @param updateTime the value for product_info.update_time
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime == null ? updateTime : (Date) updateTime.clone();;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.updater
     *
     * @return the value of product_info.updater
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.updater
     *
     * @param updater the value for product_info.updater
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.deleteflag
     *
     * @return the value of product_info.deleteflag
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.deleteflag
     *
     * @param deleteflag the value for product_info.deleteflag
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.tacticsEDID
     *
     * @return the value of product_info.tacticsEDID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getTacticsedid() {
        return tacticsedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.tacticsEDID
     *
     * @param tacticsedid the value for product_info.tacticsEDID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setTacticsedid(String tacticsedid) {
        this.tacticsedid = tacticsedid == null ? null : tacticsedid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.tacticsZRID
     *
     * @return the value of product_info.tacticsZRID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getTacticszrid() {
        return tacticszrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.tacticsZRID
     *
     * @param tacticszrid the value for product_info.tacticsZRID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setTacticszrid(String tacticszrid) {
        this.tacticszrid = tacticszrid == null ? null : tacticszrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.tacticsFKID
     *
     * @return the value of product_info.tacticsFKID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public String getTacticsfkid() {
        return tacticsfkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.tacticsFKID
     *
     * @param tacticsfkid the value for product_info.tacticsFKID
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    public void setTacticsfkid(String tacticsfkid) {
        this.tacticsfkid = tacticsfkid == null ? null : tacticsfkid.trim();
    }

    public int getQueueNum() {
        return queueNum;
    }

    public void setQueueNum(int queueNum) {
        this.queueNum = queueNum;
    }

    public int getPriorityLevel() {
        return priorityLevel;
    }

    public void setPriorityLevel(int priorityLevel) {
        this.priorityLevel = priorityLevel;
    }

    public String getTacticsKQID() {
        return tacticsKQID;
    }

    public void setTacticsKQID(String tacticsKQID) {
        this.tacticsKQID = tacticsKQID;
    }

    public int getCommodityType() {
        return commodityType;
    }

    public void setCommodityType(int commodityType) {
        this.commodityType = commodityType;
    }

    public int getCommodityChannel() {
        return commodityChannel;
    }

    public void setCommodityChannel(int commodityChannel) {
        this.commodityChannel = commodityChannel;
    }

    public int getExecuteOrder() {
        return executeOrder;
    }

    public void setExecuteOrder(int executeOrder) {
        this.executeOrder = executeOrder;
    }
}