package com.jzfq.rms.product.bean;

import java.util.Date;

public class RuleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_id
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Integer ruleId;

    /**
     * 规则编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_No
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String ruleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.parent_No
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String parentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_classification
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Integer ruleClassification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_classic_name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String ruleClassicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_description
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String ruleDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_sorce
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Integer ruleSorce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.check_items
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Integer checkItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.checkURL
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String checkurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.callURL
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String callurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.tactics_type_name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String tacticsTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.tactics_type
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Integer tacticsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_oi_Type_Name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String ruleOiTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_oi_Type
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Integer ruleOiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.state
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.create_time
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.creator
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.update_time
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.updater
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.deleteflag
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_id
     *
     * @return the value of rule_info.rule_id
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_id
     *
     * @param ruleId the value for rule_info.rule_id
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_No
     *
     * @return the value of rule_info.rule_No
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getRuleNo() {
        return ruleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_No
     *
     * @param ruleNo the value for rule_info.rule_No
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setRuleNo(String ruleNo) {
        this.ruleNo = ruleNo == null ? null : ruleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.parent_No
     *
     * @return the value of rule_info.parent_No
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getParentNo() {
        return parentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.parent_No
     *
     * @param parentNo the value for rule_info.parent_No
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setParentNo(String parentNo) {
        this.parentNo = parentNo == null ? null : parentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_classification
     *
     * @return the value of rule_info.rule_classification
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Integer getRuleClassification() {
        return ruleClassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_classification
     *
     * @param ruleClassification the value for rule_info.rule_classification
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setRuleClassification(Integer ruleClassification) {
        this.ruleClassification = ruleClassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_classic_name
     *
     * @return the value of rule_info.rule_classic_name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getRuleClassicName() {
        return ruleClassicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_classic_name
     *
     * @param ruleClassicName the value for rule_info.rule_classic_name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setRuleClassicName(String ruleClassicName) {
        this.ruleClassicName = ruleClassicName == null ? null : ruleClassicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_description
     *
     * @return the value of rule_info.rule_description
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getRuleDescription() {
        return ruleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_description
     *
     * @param ruleDescription the value for rule_info.rule_description
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setRuleDescription(String ruleDescription) {
        this.ruleDescription = ruleDescription == null ? null : ruleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_sorce
     *
     * @return the value of rule_info.rule_sorce
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Integer getRuleSorce() {
        return ruleSorce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_sorce
     *
     * @param ruleSorce the value for rule_info.rule_sorce
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setRuleSorce(Integer ruleSorce) {
        this.ruleSorce = ruleSorce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.check_items
     *
     * @return the value of rule_info.check_items
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Integer getCheckItems() {
        return checkItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.check_items
     *
     * @param checkItems the value for rule_info.check_items
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setCheckItems(Integer checkItems) {
        this.checkItems = checkItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.checkURL
     *
     * @return the value of rule_info.checkURL
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getCheckurl() {
        return checkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.checkURL
     *
     * @param checkurl the value for rule_info.checkURL
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setCheckurl(String checkurl) {
        this.checkurl = checkurl == null ? null : checkurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.callURL
     *
     * @return the value of rule_info.callURL
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getCallurl() {
        return callurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.callURL
     *
     * @param callurl the value for rule_info.callURL
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setCallurl(String callurl) {
        this.callurl = callurl == null ? null : callurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.tactics_type_name
     *
     * @return the value of rule_info.tactics_type_name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getTacticsTypeName() {
        return tacticsTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.tactics_type_name
     *
     * @param tacticsTypeName the value for rule_info.tactics_type_name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setTacticsTypeName(String tacticsTypeName) {
        this.tacticsTypeName = tacticsTypeName == null ? null : tacticsTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.tactics_type
     *
     * @return the value of rule_info.tactics_type
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Integer getTacticsType() {
        return tacticsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.tactics_type
     *
     * @param tacticsType the value for rule_info.tactics_type
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setTacticsType(Integer tacticsType) {
        this.tacticsType = tacticsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_oi_Type_Name
     *
     * @return the value of rule_info.rule_oi_Type_Name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getRuleOiTypeName() {
        return ruleOiTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_oi_Type_Name
     *
     * @param ruleOiTypeName the value for rule_info.rule_oi_Type_Name
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setRuleOiTypeName(String ruleOiTypeName) {
        this.ruleOiTypeName = ruleOiTypeName == null ? null : ruleOiTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_oi_Type
     *
     * @return the value of rule_info.rule_oi_Type
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Integer getRuleOiType() {
        return ruleOiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_oi_Type
     *
     * @param ruleOiType the value for rule_info.rule_oi_Type
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setRuleOiType(Integer ruleOiType) {
        this.ruleOiType = ruleOiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.state
     *
     * @return the value of rule_info.state
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.state
     *
     * @param state the value for rule_info.state
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.create_time
     *
     * @return the value of rule_info.create_time
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Date getCreateTime() {
        return createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.create_time
     *
     * @param createTime the value for rule_info.create_time
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.creator
     *
     * @return the value of rule_info.creator
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.creator
     *
     * @param creator the value for rule_info.creator
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.update_time
     *
     * @return the value of rule_info.update_time
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.update_time
     *
     * @param updateTime the value for rule_info.update_time
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.updater
     *
     * @return the value of rule_info.updater
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.updater
     *
     * @param updater the value for rule_info.updater
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.deleteflag
     *
     * @return the value of rule_info.deleteflag
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.deleteflag
     *
     * @param deleteflag the value for rule_info.deleteflag
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}