package com.jzfq.rms.product.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RuleInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public RuleInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRuleIdIsNull() {
            addCriterion("`rule_id` is null");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNotNull() {
            addCriterion("`rule_id` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleIdEqualTo(Integer value) {
            addCriterion("`rule_id` =", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotEqualTo(Integer value) {
            addCriterion("`rule_id` <>", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThan(Integer value) {
            addCriterion("`rule_id` >", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`rule_id` >=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThan(Integer value) {
            addCriterion("`rule_id` <", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThanOrEqualTo(Integer value) {
            addCriterion("`rule_id` <=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdIn(List<Integer> values) {
            addCriterion("`rule_id` in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotIn(List<Integer> values) {
            addCriterion("`rule_id` not in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdBetween(Integer value1, Integer value2) {
            addCriterion("`rule_id` between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`rule_id` not between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleNoIsNull() {
            addCriterion("`rule_No` is null");
            return (Criteria) this;
        }

        public Criteria andRuleNoIsNotNull() {
            addCriterion("`rule_No` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleNoEqualTo(String value) {
            addCriterion("`rule_No` =", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoNotEqualTo(String value) {
            addCriterion("`rule_No` <>", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoGreaterThan(String value) {
            addCriterion("`rule_No` >", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoGreaterThanOrEqualTo(String value) {
            addCriterion("`rule_No` >=", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoLessThan(String value) {
            addCriterion("`rule_No` <", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoLessThanOrEqualTo(String value) {
            addCriterion("`rule_No` <=", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoLike(String value) {
            addCriterion("`rule_No` like", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoNotLike(String value) {
            addCriterion("`rule_No` not like", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoIn(List<String> values) {
            addCriterion("`rule_No` in", values, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoNotIn(List<String> values) {
            addCriterion("`rule_No` not in", values, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoBetween(String value1, String value2) {
            addCriterion("`rule_No` between", value1, value2, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoNotBetween(String value1, String value2) {
            addCriterion("`rule_No` not between", value1, value2, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andParentNoIsNull() {
            addCriterion("`parent_No` is null");
            return (Criteria) this;
        }

        public Criteria andParentNoIsNotNull() {
            addCriterion("`parent_No` is not null");
            return (Criteria) this;
        }

        public Criteria andParentNoEqualTo(String value) {
            addCriterion("`parent_No` =", value, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoNotEqualTo(String value) {
            addCriterion("`parent_No` <>", value, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoGreaterThan(String value) {
            addCriterion("`parent_No` >", value, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoGreaterThanOrEqualTo(String value) {
            addCriterion("`parent_No` >=", value, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoLessThan(String value) {
            addCriterion("`parent_No` <", value, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoLessThanOrEqualTo(String value) {
            addCriterion("`parent_No` <=", value, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoLike(String value) {
            addCriterion("`parent_No` like", value, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoNotLike(String value) {
            addCriterion("`parent_No` not like", value, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoIn(List<String> values) {
            addCriterion("`parent_No` in", values, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoNotIn(List<String> values) {
            addCriterion("`parent_No` not in", values, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoBetween(String value1, String value2) {
            addCriterion("`parent_No` between", value1, value2, "parentNo");
            return (Criteria) this;
        }

        public Criteria andParentNoNotBetween(String value1, String value2) {
            addCriterion("`parent_No` not between", value1, value2, "parentNo");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationIsNull() {
            addCriterion("`rule_classification` is null");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationIsNotNull() {
            addCriterion("`rule_classification` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationEqualTo(Integer value) {
            addCriterion("`rule_classification` =", value, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationNotEqualTo(Integer value) {
            addCriterion("`rule_classification` <>", value, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationGreaterThan(Integer value) {
            addCriterion("`rule_classification` >", value, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationGreaterThanOrEqualTo(Integer value) {
            addCriterion("`rule_classification` >=", value, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationLessThan(Integer value) {
            addCriterion("`rule_classification` <", value, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationLessThanOrEqualTo(Integer value) {
            addCriterion("`rule_classification` <=", value, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationIn(List<Integer> values) {
            addCriterion("`rule_classification` in", values, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationNotIn(List<Integer> values) {
            addCriterion("`rule_classification` not in", values, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationBetween(Integer value1, Integer value2) {
            addCriterion("`rule_classification` between", value1, value2, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassificationNotBetween(Integer value1, Integer value2) {
            addCriterion("`rule_classification` not between", value1, value2, "ruleClassification");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameIsNull() {
            addCriterion("`rule_classic_name` is null");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameIsNotNull() {
            addCriterion("`rule_classic_name` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameEqualTo(String value) {
            addCriterion("`rule_classic_name` =", value, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameNotEqualTo(String value) {
            addCriterion("`rule_classic_name` <>", value, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameGreaterThan(String value) {
            addCriterion("`rule_classic_name` >", value, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameGreaterThanOrEqualTo(String value) {
            addCriterion("`rule_classic_name` >=", value, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameLessThan(String value) {
            addCriterion("`rule_classic_name` <", value, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameLessThanOrEqualTo(String value) {
            addCriterion("`rule_classic_name` <=", value, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameLike(String value) {
            addCriterion("`rule_classic_name` like", value, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameNotLike(String value) {
            addCriterion("`rule_classic_name` not like", value, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameIn(List<String> values) {
            addCriterion("`rule_classic_name` in", values, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameNotIn(List<String> values) {
            addCriterion("`rule_classic_name` not in", values, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameBetween(String value1, String value2) {
            addCriterion("`rule_classic_name` between", value1, value2, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleClassicNameNotBetween(String value1, String value2) {
            addCriterion("`rule_classic_name` not between", value1, value2, "ruleClassicName");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionIsNull() {
            addCriterion("`rule_description` is null");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionIsNotNull() {
            addCriterion("`rule_description` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionEqualTo(String value) {
            addCriterion("`rule_description` =", value, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionNotEqualTo(String value) {
            addCriterion("`rule_description` <>", value, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionGreaterThan(String value) {
            addCriterion("`rule_description` >", value, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("`rule_description` >=", value, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionLessThan(String value) {
            addCriterion("`rule_description` <", value, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionLessThanOrEqualTo(String value) {
            addCriterion("`rule_description` <=", value, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionLike(String value) {
            addCriterion("`rule_description` like", value, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionNotLike(String value) {
            addCriterion("`rule_description` not like", value, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionIn(List<String> values) {
            addCriterion("`rule_description` in", values, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionNotIn(List<String> values) {
            addCriterion("`rule_description` not in", values, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionBetween(String value1, String value2) {
            addCriterion("`rule_description` between", value1, value2, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleDescriptionNotBetween(String value1, String value2) {
            addCriterion("`rule_description` not between", value1, value2, "ruleDescription");
            return (Criteria) this;
        }

        public Criteria andRuleSorceIsNull() {
            addCriterion("`rule_sorce` is null");
            return (Criteria) this;
        }

        public Criteria andRuleSorceIsNotNull() {
            addCriterion("`rule_sorce` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleSorceEqualTo(Integer value) {
            addCriterion("`rule_sorce` =", value, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceNotEqualTo(Integer value) {
            addCriterion("`rule_sorce` <>", value, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceGreaterThan(Integer value) {
            addCriterion("`rule_sorce` >", value, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceGreaterThanOrEqualTo(Integer value) {
            addCriterion("`rule_sorce` >=", value, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceLessThan(Integer value) {
            addCriterion("`rule_sorce` <", value, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceLessThanOrEqualTo(Integer value) {
            addCriterion("`rule_sorce` <=", value, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceIn(List<Integer> values) {
            addCriterion("`rule_sorce` in", values, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceNotIn(List<Integer> values) {
            addCriterion("`rule_sorce` not in", values, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceBetween(Integer value1, Integer value2) {
            addCriterion("`rule_sorce` between", value1, value2, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andRuleSorceNotBetween(Integer value1, Integer value2) {
            addCriterion("`rule_sorce` not between", value1, value2, "ruleSorce");
            return (Criteria) this;
        }

        public Criteria andCheckItemsIsNull() {
            addCriterion("`check_items` is null");
            return (Criteria) this;
        }

        public Criteria andCheckItemsIsNotNull() {
            addCriterion("`check_items` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckItemsEqualTo(Integer value) {
            addCriterion("`check_items` =", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsNotEqualTo(Integer value) {
            addCriterion("`check_items` <>", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsGreaterThan(Integer value) {
            addCriterion("`check_items` >", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsGreaterThanOrEqualTo(Integer value) {
            addCriterion("`check_items` >=", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsLessThan(Integer value) {
            addCriterion("`check_items` <", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsLessThanOrEqualTo(Integer value) {
            addCriterion("`check_items` <=", value, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsIn(List<Integer> values) {
            addCriterion("`check_items` in", values, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsNotIn(List<Integer> values) {
            addCriterion("`check_items` not in", values, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsBetween(Integer value1, Integer value2) {
            addCriterion("`check_items` between", value1, value2, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckItemsNotBetween(Integer value1, Integer value2) {
            addCriterion("`check_items` not between", value1, value2, "checkItems");
            return (Criteria) this;
        }

        public Criteria andCheckurlIsNull() {
            addCriterion("`checkURL` is null");
            return (Criteria) this;
        }

        public Criteria andCheckurlIsNotNull() {
            addCriterion("`checkURL` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckurlEqualTo(String value) {
            addCriterion("`checkURL` =", value, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlNotEqualTo(String value) {
            addCriterion("`checkURL` <>", value, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlGreaterThan(String value) {
            addCriterion("`checkURL` >", value, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlGreaterThanOrEqualTo(String value) {
            addCriterion("`checkURL` >=", value, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlLessThan(String value) {
            addCriterion("`checkURL` <", value, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlLessThanOrEqualTo(String value) {
            addCriterion("`checkURL` <=", value, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlLike(String value) {
            addCriterion("`checkURL` like", value, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlNotLike(String value) {
            addCriterion("`checkURL` not like", value, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlIn(List<String> values) {
            addCriterion("`checkURL` in", values, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlNotIn(List<String> values) {
            addCriterion("`checkURL` not in", values, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlBetween(String value1, String value2) {
            addCriterion("`checkURL` between", value1, value2, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCheckurlNotBetween(String value1, String value2) {
            addCriterion("`checkURL` not between", value1, value2, "checkurl");
            return (Criteria) this;
        }

        public Criteria andCallurlIsNull() {
            addCriterion("`callURL` is null");
            return (Criteria) this;
        }

        public Criteria andCallurlIsNotNull() {
            addCriterion("`callURL` is not null");
            return (Criteria) this;
        }

        public Criteria andCallurlEqualTo(String value) {
            addCriterion("`callURL` =", value, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlNotEqualTo(String value) {
            addCriterion("`callURL` <>", value, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlGreaterThan(String value) {
            addCriterion("`callURL` >", value, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlGreaterThanOrEqualTo(String value) {
            addCriterion("`callURL` >=", value, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlLessThan(String value) {
            addCriterion("`callURL` <", value, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlLessThanOrEqualTo(String value) {
            addCriterion("`callURL` <=", value, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlLike(String value) {
            addCriterion("`callURL` like", value, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlNotLike(String value) {
            addCriterion("`callURL` not like", value, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlIn(List<String> values) {
            addCriterion("`callURL` in", values, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlNotIn(List<String> values) {
            addCriterion("`callURL` not in", values, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlBetween(String value1, String value2) {
            addCriterion("`callURL` between", value1, value2, "callurl");
            return (Criteria) this;
        }

        public Criteria andCallurlNotBetween(String value1, String value2) {
            addCriterion("`callURL` not between", value1, value2, "callurl");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameIsNull() {
            addCriterion("`tactics_type_name` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameIsNotNull() {
            addCriterion("`tactics_type_name` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameEqualTo(String value) {
            addCriterion("`tactics_type_name` =", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameNotEqualTo(String value) {
            addCriterion("`tactics_type_name` <>", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameGreaterThan(String value) {
            addCriterion("`tactics_type_name` >", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`tactics_type_name` >=", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameLessThan(String value) {
            addCriterion("`tactics_type_name` <", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`tactics_type_name` <=", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameLike(String value) {
            addCriterion("`tactics_type_name` like", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameNotLike(String value) {
            addCriterion("`tactics_type_name` not like", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameIn(List<String> values) {
            addCriterion("`tactics_type_name` in", values, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameNotIn(List<String> values) {
            addCriterion("`tactics_type_name` not in", values, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameBetween(String value1, String value2) {
            addCriterion("`tactics_type_name` between", value1, value2, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameNotBetween(String value1, String value2) {
            addCriterion("`tactics_type_name` not between", value1, value2, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeIsNull() {
            addCriterion("`tactics_type` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeIsNotNull() {
            addCriterion("`tactics_type` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeEqualTo(Integer value) {
            addCriterion("`tactics_type` =", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNotEqualTo(Integer value) {
            addCriterion("`tactics_type` <>", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeGreaterThan(Integer value) {
            addCriterion("`tactics_type` >", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`tactics_type` >=", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeLessThan(Integer value) {
            addCriterion("`tactics_type` <", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`tactics_type` <=", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeIn(List<Integer> values) {
            addCriterion("`tactics_type` in", values, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNotIn(List<Integer> values) {
            addCriterion("`tactics_type` not in", values, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_type` between", value1, value2, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_type` not between", value1, value2, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameIsNull() {
            addCriterion("`rule_oi_Type_Name` is null");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameIsNotNull() {
            addCriterion("`rule_oi_Type_Name` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameEqualTo(String value) {
            addCriterion("`rule_oi_Type_Name` =", value, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameNotEqualTo(String value) {
            addCriterion("`rule_oi_Type_Name` <>", value, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameGreaterThan(String value) {
            addCriterion("`rule_oi_Type_Name` >", value, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`rule_oi_Type_Name` >=", value, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameLessThan(String value) {
            addCriterion("`rule_oi_Type_Name` <", value, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`rule_oi_Type_Name` <=", value, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameLike(String value) {
            addCriterion("`rule_oi_Type_Name` like", value, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameNotLike(String value) {
            addCriterion("`rule_oi_Type_Name` not like", value, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameIn(List<String> values) {
            addCriterion("`rule_oi_Type_Name` in", values, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameNotIn(List<String> values) {
            addCriterion("`rule_oi_Type_Name` not in", values, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameBetween(String value1, String value2) {
            addCriterion("`rule_oi_Type_Name` between", value1, value2, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNameNotBetween(String value1, String value2) {
            addCriterion("`rule_oi_Type_Name` not between", value1, value2, "ruleOiTypeName");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeIsNull() {
            addCriterion("`rule_oi_Type` is null");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeIsNotNull() {
            addCriterion("`rule_oi_Type` is not null");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeEqualTo(Integer value) {
            addCriterion("`rule_oi_Type` =", value, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNotEqualTo(Integer value) {
            addCriterion("`rule_oi_Type` <>", value, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeGreaterThan(Integer value) {
            addCriterion("`rule_oi_Type` >", value, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`rule_oi_Type` >=", value, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeLessThan(Integer value) {
            addCriterion("`rule_oi_Type` <", value, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`rule_oi_Type` <=", value, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeIn(List<Integer> values) {
            addCriterion("`rule_oi_Type` in", values, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNotIn(List<Integer> values) {
            addCriterion("`rule_oi_Type` not in", values, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeBetween(Integer value1, Integer value2) {
            addCriterion("`rule_oi_Type` between", value1, value2, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andRuleOiTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`rule_oi_Type` not between", value1, value2, "ruleOiType");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("`creator` is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("`creator` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("`creator` =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("`creator` <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("`creator` >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("`creator` >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("`creator` <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("`creator` <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("`creator` like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("`creator` not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("`creator` in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("`creator` not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("`creator` between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("`creator` not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("`updater` is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("`updater` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("`updater` =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("`updater` <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("`updater` >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("`updater` >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("`updater` <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("`updater` <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("`updater` like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("`updater` not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("`updater` in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("`updater` not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("`updater` between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("`updater` not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("`deleteflag` is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("`deleteflag` is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("`deleteflag` =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("`deleteflag` <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("`deleteflag` >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("`deleteflag` >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("`deleteflag` <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("`deleteflag` <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("`deleteflag` in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("`deleteflag` not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("`deleteflag` between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("`deleteflag` not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rule_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 22 13:02:16 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}