package com.jzfq.rms.product.bean;

import java.util.Date;

public class RuleParamSets {
    /**
     * 规则参数ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.rule_param_ID
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private Integer ruleParamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.rule_param_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private String ruleParamNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.rule_param_serial
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private Integer ruleParamSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.rule_id
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private Integer ruleId;

    /**
     * 规则编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.rule_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private String ruleNo;

    /**
     * 规则分类名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.rule_classic_name
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private String ruleClassicName;

    /**
     * 判断Key
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.matches_key
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private Integer matchesKey;

    /**
     * 判断符号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.matches_key_name
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private String matchesKeyName;

    /**
     * 判断值
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.matches_value
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private String matchesValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.rule_sets_ID
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private Integer ruleSetsId;

    /**
     * 规则集编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.rule_sets_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private String ruleSetsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.create_time
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.creator
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.update_time
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_param_sets.updater
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.rule_param_ID
     *
     * @return the value of rule_param_sets.rule_param_ID
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public Integer getRuleParamId() {
        return ruleParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.rule_param_ID
     *
     * @param ruleParamId the value for rule_param_sets.rule_param_ID
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setRuleParamId(Integer ruleParamId) {
        this.ruleParamId = ruleParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.rule_param_No
     *
     * @return the value of rule_param_sets.rule_param_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public String getRuleParamNo() {
        return ruleParamNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.rule_param_No
     *
     * @param ruleParamNo the value for rule_param_sets.rule_param_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setRuleParamNo(String ruleParamNo) {
        this.ruleParamNo = ruleParamNo == null ? null : ruleParamNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.rule_param_serial
     *
     * @return the value of rule_param_sets.rule_param_serial
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public Integer getRuleParamSerial() {
        return ruleParamSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.rule_param_serial
     *
     * @param ruleParamSerial the value for rule_param_sets.rule_param_serial
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setRuleParamSerial(Integer ruleParamSerial) {
        this.ruleParamSerial = ruleParamSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.rule_id
     *
     * @return the value of rule_param_sets.rule_id
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.rule_id
     *
     * @param ruleId the value for rule_param_sets.rule_id
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.rule_No
     *
     * @return the value of rule_param_sets.rule_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public String getRuleNo() {
        return ruleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.rule_No
     *
     * @param ruleNo the value for rule_param_sets.rule_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setRuleNo(String ruleNo) {
        this.ruleNo = ruleNo == null ? null : ruleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.rule_classic_name
     *
     * @return the value of rule_param_sets.rule_classic_name
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public String getRuleClassicName() {
        return ruleClassicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.rule_classic_name
     *
     * @param ruleClassicName the value for rule_param_sets.rule_classic_name
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setRuleClassicName(String ruleClassicName) {
        this.ruleClassicName = ruleClassicName == null ? null : ruleClassicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.matches_key
     *
     * @return the value of rule_param_sets.matches_key
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public Integer getMatchesKey() {
        return matchesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.matches_key
     *
     * @param matchesKey the value for rule_param_sets.matches_key
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setMatchesKey(Integer matchesKey) {
        this.matchesKey = matchesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.matches_key_name
     *
     * @return the value of rule_param_sets.matches_key_name
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public String getMatchesKeyName() {
        return matchesKeyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.matches_key_name
     *
     * @param matchesKeyName the value for rule_param_sets.matches_key_name
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setMatchesKeyName(String matchesKeyName) {
        this.matchesKeyName = matchesKeyName == null ? null : matchesKeyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.matches_value
     *
     * @return the value of rule_param_sets.matches_value
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public String getMatchesValue() {
        return matchesValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.matches_value
     *
     * @param matchesValue the value for rule_param_sets.matches_value
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setMatchesValue(String matchesValue) {
        this.matchesValue = matchesValue == null ? null : matchesValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.rule_sets_ID
     *
     * @return the value of rule_param_sets.rule_sets_ID
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public Integer getRuleSetsId() {
        return ruleSetsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.rule_sets_ID
     *
     * @param ruleSetsId the value for rule_param_sets.rule_sets_ID
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setRuleSetsId(Integer ruleSetsId) {
        this.ruleSetsId = ruleSetsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.rule_sets_No
     *
     * @return the value of rule_param_sets.rule_sets_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public String getRuleSetsNo() {
        return ruleSetsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.rule_sets_No
     *
     * @param ruleSetsNo the value for rule_param_sets.rule_sets_No
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setRuleSetsNo(String ruleSetsNo) {
        this.ruleSetsNo = ruleSetsNo == null ? null : ruleSetsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.create_time
     *
     * @return the value of rule_param_sets.create_time
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.create_time
     *
     * @param createTime the value for rule_param_sets.create_time
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.creator
     *
     * @return the value of rule_param_sets.creator
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.creator
     *
     * @param creator the value for rule_param_sets.creator
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.update_time
     *
     * @return the value of rule_param_sets.update_time
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.update_time
     *
     * @param updateTime the value for rule_param_sets.update_time
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_param_sets.updater
     *
     * @return the value of rule_param_sets.updater
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_param_sets.updater
     *
     * @param updater the value for rule_param_sets.updater
     *
     * @mbg.generated Wed Nov 22 13:32:09 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}