package com.jzfq.rms.product.bean;

import java.util.Date;
import java.util.List;
import java.util.Map;

public class RuleSetsDisplay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.rule_sets_ID
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Integer ruleSetsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.rule_sets_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String ruleSetsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.rule_sets_name
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String ruleSetsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.rule_sets_Descripton
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String ruleSetsDescripton;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.rule_sets_serial
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Integer ruleSetsSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.execute_Key
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Integer executeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.execute_Key_Content
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String executeKeyContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.oi_Type
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Integer oiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.oi_Type_Name
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String oiTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.hit_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String hitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.mail_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String mailSets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.weight_score
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Integer weightScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.tactics_id
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Integer tacticsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.tactics_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String tacticsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.rule_sets_state
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Integer ruleSetsState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.create_Time
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.creator
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.update_Time
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.updater
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.rule_param_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private List<RuleParamSets> ruleParamSets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_sets.decision_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    private Map decisionSets;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.rule_sets_ID
     *
     * @return the value of rule_sets.rule_sets_ID
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Integer getRuleSetsId() {
        return ruleSetsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.rule_sets_ID
     *
     * @param ruleSetsId the value for rule_sets.rule_sets_ID
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setRuleSetsId(Integer ruleSetsId) {
        this.ruleSetsId = ruleSetsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.rule_sets_No
     *
     * @return the value of rule_sets.rule_sets_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getRuleSetsNo() {
        return ruleSetsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.rule_sets_No
     *
     * @param ruleSetsNo the value for rule_sets.rule_sets_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setRuleSetsNo(String ruleSetsNo) {
        this.ruleSetsNo = ruleSetsNo == null ? null : ruleSetsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.rule_sets_name
     *
     * @return the value of rule_sets.rule_sets_name
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getRuleSetsName() {
        return ruleSetsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.rule_sets_name
     *
     * @param ruleSetsName the value for rule_sets.rule_sets_name
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setRuleSetsName(String ruleSetsName) {
        this.ruleSetsName = ruleSetsName == null ? null : ruleSetsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.rule_sets_Descripton
     *
     * @return the value of rule_sets.rule_sets_Descripton
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getRuleSetsDescripton() {
        return ruleSetsDescripton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.rule_sets_Descripton
     *
     * @param ruleSetsDescripton the value for rule_sets.rule_sets_Descripton
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setRuleSetsDescripton(String ruleSetsDescripton) {
        this.ruleSetsDescripton = ruleSetsDescripton == null ? null : ruleSetsDescripton.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.rule_sets_serial
     *
     * @return the value of rule_sets.rule_sets_serial
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Integer getRuleSetsSerial() {
        return ruleSetsSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.rule_sets_serial
     *
     * @param ruleSetsSerial the value for rule_sets.rule_sets_serial
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setRuleSetsSerial(Integer ruleSetsSerial) {
        this.ruleSetsSerial = ruleSetsSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.execute_Key
     *
     * @return the value of rule_sets.execute_Key
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Integer getExecuteKey() {
        return executeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.execute_Key
     *
     * @param executeKey the value for rule_sets.execute_Key
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setExecuteKey(Integer executeKey) {
        this.executeKey = executeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.execute_Key_Content
     *
     * @return the value of rule_sets.execute_Key_Content
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getExecuteKeyContent() {
        return executeKeyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.execute_Key_Content
     *
     * @param executeKeyContent the value for rule_sets.execute_Key_Content
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setExecuteKeyContent(String executeKeyContent) {
        this.executeKeyContent = executeKeyContent == null ? null : executeKeyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.oi_Type
     *
     * @return the value of rule_sets.oi_Type
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Integer getOiType() {
        return oiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.oi_Type
     *
     * @param oiType the value for rule_sets.oi_Type
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setOiType(Integer oiType) {
        this.oiType = oiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.oi_Type_Name
     *
     * @return the value of rule_sets.oi_Type_Name
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getOiTypeName() {
        return oiTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.oi_Type_Name
     *
     * @param oiTypeName the value for rule_sets.oi_Type_Name
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setOiTypeName(String oiTypeName) {
        this.oiTypeName = oiTypeName == null ? null : oiTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.hit_No
     *
     * @return the value of rule_sets.hit_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getHitNo() {
        return hitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.hit_No
     *
     * @param hitNo the value for rule_sets.hit_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setHitNo(String hitNo) {
        this.hitNo = hitNo == null ? null : hitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.mail_Sets
     *
     * @return the value of rule_sets.mail_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getMailSets() {
        return mailSets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.mail_Sets
     *
     * @param mailSets the value for rule_sets.mail_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setMailSets(String mailSets) {
        this.mailSets = mailSets == null ? null : mailSets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.weight_score
     *
     * @return the value of rule_sets.weight_score
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Integer getWeightScore() {
        return weightScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.weight_score
     *
     * @param weightScore the value for rule_sets.weight_score
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setWeightScore(Integer weightScore) {
        this.weightScore = weightScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.tactics_id
     *
     * @return the value of rule_sets.tactics_id
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Integer getTacticsId() {
        return tacticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.tactics_id
     *
     * @param tacticsId the value for rule_sets.tactics_id
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setTacticsId(Integer tacticsId) {
        this.tacticsId = tacticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.tactics_No
     *
     * @return the value of rule_sets.tactics_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getTacticsNo() {
        return tacticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.tactics_No
     *
     * @param tacticsNo the value for rule_sets.tactics_No
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setTacticsNo(String tacticsNo) {
        this.tacticsNo = tacticsNo == null ? null : tacticsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.rule_sets_state
     *
     * @return the value of rule_sets.rule_sets_state
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Integer getRuleSetsState() {
        return ruleSetsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.rule_sets_state
     *
     * @param ruleSetsState the value for rule_sets.rule_sets_state
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setRuleSetsState(Integer ruleSetsState) {
        this.ruleSetsState = ruleSetsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.create_Time
     *
     * @return the value of rule_sets.create_Time
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.create_Time
     *
     * @param createTime the value for rule_sets.create_Time
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime == null ? createTime : (Date) createTime.clone();

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.creator
     *
     * @return the value of rule_sets.creator
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.creator
     *
     * @param creator the value for rule_sets.creator
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.update_Time
     *
     * @return the value of rule_sets.update_Time
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.update_Time
     *
     * @param updateTime the value for rule_sets.update_Time
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.updater
     *
     * @return the value of rule_sets.updater
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.updater
     *
     * @param updater the value for rule_sets.updater
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.rule_param_Sets
     *
     * @return the value of rule_sets.rule_param_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public List<RuleParamSets> getRuleParamSets() {
        return ruleParamSets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.rule_param_Sets
     *
     * @param ruleParamSets the value for rule_sets.rule_param_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setRuleParamSets(List<RuleParamSets> ruleParamSets) {
        this.ruleParamSets = ruleParamSets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_sets.decision_Sets
     *
     * @return the value of rule_sets.decision_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public Map getDecisionSets() {
        return decisionSets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_sets.decision_Sets
     *
     * @param decisionSets the value for rule_sets.decision_Sets
     *
     * @mbg.generated Thu Nov 16 14:14:21 CST 2017
     */
    public void setDecisionSets(Map decisionSets) {
        this.decisionSets = decisionSets;
    }
}