package com.jzfq.rms.product.bean;

import com.alibaba.fastjson.annotation.JSONField;
import com.jzfq.rms.product.common.Page;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.Range;
import org.springframework.format.annotation.NumberFormat;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.util.Date;

/**
 * 策略记录表实体类
 * @author 大连桔子分期科技有限公司
 * @date 2018年1月24日 09:45:55
 */
public class TacticsRecord extends Page {
    /**
     * 策略id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_id
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    private Integer tacticsId;

    /**
     * 策略名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    @NotBlank(message = "策略名称不能为空！")
    private String tacticsName;

    /**
     * 策略编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_No
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    @NotBlank(message = "策略编号不能为空！")
    private String tacticsNo;

    /**
     * 策略类型名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_type_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    private String tacticsTypeName;

    /**
     * 策略类型
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_type
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    @NotBlank(message = "策略类型不能为空！")
    @Pattern(regexp = "^[0-9]\\d*$", message = "策略类型必须为数字！")
    private String tacticsType;

    /**
     * 开启状态名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_state_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    private String tacticsStateName;

    /**
     * 开启状态（0：启用；1：停用）
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_state
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    @NotBlank(message = "开启状态不能为空！")
    @Pattern(regexp = "^[0-1]$", message = "开启状态必须为数字！")
    private String tacticsState;

    /**
     * 自动开关名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_switch_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    private String tacticsSwitchName;

    /**
     * 策略自动开关
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_switch
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    @NotBlank(message = "策略自动开关不能为空！")
    @Pattern(regexp = "^[0-5]$", message = "策略自动开关不能为空且必须为数字！")
    private String tacticsSwitch;

    /**
     * 备注
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.tactics_remark
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    private String tacticsRemark;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.create_time
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * 创建人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.creator
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    private String creator;

    /**
     * 更新时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.update_time
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * 更新人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.updater
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    private String updater;

    /**
     * 删除flag（0：可用、1：已删除）
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.deleteflag
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    private Integer deleteflag;

    /**
     * 规则参数JSON
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tactics_record.rule_sets
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    @NotNull(message = "不能为空")
    private Object ruleSets;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_id
     *
     * @return the value of tactics_record.tactics_id
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public Integer getTacticsId() {
        return tacticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_id
     *
     * @param tacticsId the value for tactics_record.tactics_id
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsId(Integer tacticsId) {
        this.tacticsId = tacticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_name
     *
     * @return the value of tactics_record.tactics_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsName() {
        return tacticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_name
     *
     * @param tacticsName the value for tactics_record.tactics_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsName(String tacticsName) {
        this.tacticsName = tacticsName == null ? null : tacticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_No
     *
     * @return the value of tactics_record.tactics_No
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsNo() {
        return tacticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_No
     *
     * @param tacticsNo the value for tactics_record.tactics_No
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsNo(String tacticsNo) {
        this.tacticsNo = tacticsNo == null ? null : tacticsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_type_name
     *
     * @return the value of tactics_record.tactics_type_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsTypeName() {
        return tacticsTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_type_name
     *
     * @param tacticsTypeName the value for tactics_record.tactics_type_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsTypeName(String tacticsTypeName) {
        this.tacticsTypeName = tacticsTypeName == null ? null : tacticsTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_type
     *
     * @return the value of tactics_record.tactics_type
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsType() {
        return tacticsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_type
     *
     * @param tacticsType the value for tactics_record.tactics_type
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsType(String tacticsType) {
        this.tacticsType = tacticsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_state_name
     *
     * @return the value of tactics_record.tactics_state_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsStateName() {
        return tacticsStateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_state_name
     *
     * @param tacticsStateName the value for tactics_record.tactics_state_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsStateName(String tacticsStateName) {
        this.tacticsStateName = tacticsStateName == null ? null : tacticsStateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_state
     *
     * @return the value of tactics_record.tactics_state
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsState() {
        return tacticsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_state
     *
     * @param tacticsState the value for tactics_record.tactics_state
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsState(String tacticsState) {
        this.tacticsState = tacticsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_switch_name
     *
     * @return the value of tactics_record.tactics_switch_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsSwitchName() {
        return tacticsSwitchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_switch_name
     *
     * @param tacticsSwitchName the value for tactics_record.tactics_switch_name
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsSwitchName(String tacticsSwitchName) {
        this.tacticsSwitchName = tacticsSwitchName == null ? null : tacticsSwitchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_switch
     *
     * @return the value of tactics_record.tactics_switch
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsSwitch() {
        return tacticsSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_switch
     *
     * @param tacticsSwitch the value for tactics_record.tactics_switch
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsSwitch(String tacticsSwitch) {
        this.tacticsSwitch = tacticsSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.tactics_remark
     *
     * @return the value of tactics_record.tactics_remark
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getTacticsRemark() {
        return tacticsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.tactics_remark
     *
     * @param tacticsRemark the value for tactics_record.tactics_remark
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setTacticsRemark(String tacticsRemark) {
        this.tacticsRemark = tacticsRemark == null ? null : tacticsRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.create_time
     *
     * @return the value of tactics_record.create_time
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.create_time
     *
     * @param createTime the value for tactics_record.create_time
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime == null ? createTime : (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.creator
     *
     * @return the value of tactics_record.creator
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.creator
     *
     * @param creator the value for tactics_record.creator
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.update_time
     *
     * @return the value of tactics_record.update_time
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.update_time
     *
     * @param updateTime the value for tactics_record.update_time
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime == null ? updateTime : (Date) updateTime.clone();    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.updater
     *
     * @return the value of tactics_record.updater
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.updater
     *
     * @param updater the value for tactics_record.updater
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.deleteflag
     *
     * @return the value of tactics_record.deleteflag
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.deleteflag
     *
     * @param deleteflag the value for tactics_record.deleteflag
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tactics_record.rule_sets
     *
     * @return the value of tactics_record.rule_sets
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public Object getRuleSets() {
        return ruleSets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tactics_record.rule_sets
     *
     * @param ruleSets the value for tactics_record.rule_sets
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setRuleSets(Object ruleSets) {
        this.ruleSets = ruleSets;
    }

    @Override
    public String toString() {
        return "TacticsRecord{" +
                "tacticsSwitchName='" + tacticsSwitchName + '\'' +
                ", tacticsSwitch='" + tacticsSwitch + '\'' +
                '}';
    }
}