package com.jzfq.rms.product.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TacticsRecordExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public TacticsRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTacticsIdIsNull() {
            addCriterion("`tactics_id` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsIdIsNotNull() {
            addCriterion("`tactics_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsIdEqualTo(Integer value) {
            addCriterion("`tactics_id` =", value, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdNotEqualTo(Integer value) {
            addCriterion("`tactics_id` <>", value, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdGreaterThan(Integer value) {
            addCriterion("`tactics_id` >", value, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`tactics_id` >=", value, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdLessThan(Integer value) {
            addCriterion("`tactics_id` <", value, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdLessThanOrEqualTo(Integer value) {
            addCriterion("`tactics_id` <=", value, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdIn(List<Integer> values) {
            addCriterion("`tactics_id` in", values, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdNotIn(List<Integer> values) {
            addCriterion("`tactics_id` not in", values, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_id` between", value1, value2, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_id` not between", value1, value2, "tacticsId");
            return (Criteria) this;
        }

        public Criteria andTacticsNameIsNull() {
            addCriterion("`tactics_name` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsNameIsNotNull() {
            addCriterion("`tactics_name` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsNameEqualTo(String value) {
            addCriterion("`tactics_name` =", value, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameNotEqualTo(String value) {
            addCriterion("`tactics_name` <>", value, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameGreaterThan(String value) {
            addCriterion("`tactics_name` >", value, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameGreaterThanOrEqualTo(String value) {
            addCriterion("`tactics_name` >=", value, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameLessThan(String value) {
            addCriterion("`tactics_name` <", value, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameLessThanOrEqualTo(String value) {
            addCriterion("`tactics_name` <=", value, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameLike(String value) {
            addCriterion("`tactics_name` like", value, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameNotLike(String value) {
            addCriterion("`tactics_name` not like", value, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameIn(List<String> values) {
            addCriterion("`tactics_name` in", values, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameNotIn(List<String> values) {
            addCriterion("`tactics_name` not in", values, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameBetween(String value1, String value2) {
            addCriterion("`tactics_name` between", value1, value2, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNameNotBetween(String value1, String value2) {
            addCriterion("`tactics_name` not between", value1, value2, "tacticsName");
            return (Criteria) this;
        }

        public Criteria andTacticsNoIsNull() {
            addCriterion("`tactics_No` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsNoIsNotNull() {
            addCriterion("`tactics_No` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsNoEqualTo(String value) {
            addCriterion("`tactics_No` =", value, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoNotEqualTo(String value) {
            addCriterion("`tactics_No` <>", value, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoGreaterThan(String value) {
            addCriterion("`tactics_No` >", value, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoGreaterThanOrEqualTo(String value) {
            addCriterion("`tactics_No` >=", value, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoLessThan(String value) {
            addCriterion("`tactics_No` <", value, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoLessThanOrEqualTo(String value) {
            addCriterion("`tactics_No` <=", value, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoLike(String value) {
            addCriterion("`tactics_No` like", value, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoNotLike(String value) {
            addCriterion("`tactics_No` not like", value, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoIn(List<String> values) {
            addCriterion("`tactics_No` in", values, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoNotIn(List<String> values) {
            addCriterion("`tactics_No` not in", values, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoBetween(String value1, String value2) {
            addCriterion("`tactics_No` between", value1, value2, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsNoNotBetween(String value1, String value2) {
            addCriterion("`tactics_No` not between", value1, value2, "tacticsNo");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameIsNull() {
            addCriterion("`tactics_type_name` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameIsNotNull() {
            addCriterion("`tactics_type_name` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameEqualTo(String value) {
            addCriterion("`tactics_type_name` =", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameNotEqualTo(String value) {
            addCriterion("`tactics_type_name` <>", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameGreaterThan(String value) {
            addCriterion("`tactics_type_name` >", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`tactics_type_name` >=", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameLessThan(String value) {
            addCriterion("`tactics_type_name` <", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameLessThanOrEqualTo(String value) {
            addCriterion("`tactics_type_name` <=", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameLike(String value) {
            addCriterion("`tactics_type_name` like", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameNotLike(String value) {
            addCriterion("`tactics_type_name` not like", value, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameIn(List<String> values) {
            addCriterion("`tactics_type_name` in", values, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameNotIn(List<String> values) {
            addCriterion("`tactics_type_name` not in", values, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameBetween(String value1, String value2) {
            addCriterion("`tactics_type_name` between", value1, value2, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNameNotBetween(String value1, String value2) {
            addCriterion("`tactics_type_name` not between", value1, value2, "tacticsTypeName");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeIsNull() {
            addCriterion("`tactics_type` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeIsNotNull() {
            addCriterion("`tactics_type` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeEqualTo(Integer value) {
            addCriterion("`tactics_type` =", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNotEqualTo(Integer value) {
            addCriterion("`tactics_type` <>", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeGreaterThan(Integer value) {
            addCriterion("`tactics_type` >", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`tactics_type` >=", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeLessThan(Integer value) {
            addCriterion("`tactics_type` <", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`tactics_type` <=", value, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeIn(List<Integer> values) {
            addCriterion("`tactics_type` in", values, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNotIn(List<Integer> values) {
            addCriterion("`tactics_type` not in", values, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_type` between", value1, value2, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_type` not between", value1, value2, "tacticsType");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameIsNull() {
            addCriterion("`tactics_state_name` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameIsNotNull() {
            addCriterion("`tactics_state_name` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameEqualTo(String value) {
            addCriterion("`tactics_state_name` =", value, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameNotEqualTo(String value) {
            addCriterion("`tactics_state_name` <>", value, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameGreaterThan(String value) {
            addCriterion("`tactics_state_name` >", value, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameGreaterThanOrEqualTo(String value) {
            addCriterion("`tactics_state_name` >=", value, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameLessThan(String value) {
            addCriterion("`tactics_state_name` <", value, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameLessThanOrEqualTo(String value) {
            addCriterion("`tactics_state_name` <=", value, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameLike(String value) {
            addCriterion("`tactics_state_name` like", value, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameNotLike(String value) {
            addCriterion("`tactics_state_name` not like", value, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameIn(List<String> values) {
            addCriterion("`tactics_state_name` in", values, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameNotIn(List<String> values) {
            addCriterion("`tactics_state_name` not in", values, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameBetween(String value1, String value2) {
            addCriterion("`tactics_state_name` between", value1, value2, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNameNotBetween(String value1, String value2) {
            addCriterion("`tactics_state_name` not between", value1, value2, "tacticsStateName");
            return (Criteria) this;
        }

        public Criteria andTacticsStateIsNull() {
            addCriterion("`tactics_state` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsStateIsNotNull() {
            addCriterion("`tactics_state` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsStateEqualTo(Integer value) {
            addCriterion("`tactics_state` =", value, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNotEqualTo(Integer value) {
            addCriterion("`tactics_state` <>", value, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateGreaterThan(Integer value) {
            addCriterion("`tactics_state` >", value, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("`tactics_state` >=", value, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateLessThan(Integer value) {
            addCriterion("`tactics_state` <", value, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateLessThanOrEqualTo(Integer value) {
            addCriterion("`tactics_state` <=", value, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateIn(List<Integer> values) {
            addCriterion("`tactics_state` in", values, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNotIn(List<Integer> values) {
            addCriterion("`tactics_state` not in", values, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_state` between", value1, value2, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsStateNotBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_state` not between", value1, value2, "tacticsState");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameIsNull() {
            addCriterion("`tactics_switch_name` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameIsNotNull() {
            addCriterion("`tactics_switch_name` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameEqualTo(String value) {
            addCriterion("`tactics_switch_name` =", value, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameNotEqualTo(String value) {
            addCriterion("`tactics_switch_name` <>", value, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameGreaterThan(String value) {
            addCriterion("`tactics_switch_name` >", value, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameGreaterThanOrEqualTo(String value) {
            addCriterion("`tactics_switch_name` >=", value, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameLessThan(String value) {
            addCriterion("`tactics_switch_name` <", value, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameLessThanOrEqualTo(String value) {
            addCriterion("`tactics_switch_name` <=", value, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameLike(String value) {
            addCriterion("`tactics_switch_name` like", value, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameNotLike(String value) {
            addCriterion("`tactics_switch_name` not like", value, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameIn(List<String> values) {
            addCriterion("`tactics_switch_name` in", values, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameNotIn(List<String> values) {
            addCriterion("`tactics_switch_name` not in", values, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameBetween(String value1, String value2) {
            addCriterion("`tactics_switch_name` between", value1, value2, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNameNotBetween(String value1, String value2) {
            addCriterion("`tactics_switch_name` not between", value1, value2, "tacticsSwitchName");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchIsNull() {
            addCriterion("`tactics_switch` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchIsNotNull() {
            addCriterion("`tactics_switch` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchEqualTo(Integer value) {
            addCriterion("`tactics_switch` =", value, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNotEqualTo(Integer value) {
            addCriterion("`tactics_switch` <>", value, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchGreaterThan(Integer value) {
            addCriterion("`tactics_switch` >", value, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("`tactics_switch` >=", value, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchLessThan(Integer value) {
            addCriterion("`tactics_switch` <", value, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("`tactics_switch` <=", value, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchIn(List<Integer> values) {
            addCriterion("`tactics_switch` in", values, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNotIn(List<Integer> values) {
            addCriterion("`tactics_switch` not in", values, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_switch` between", value1, value2, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("`tactics_switch` not between", value1, value2, "tacticsSwitch");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkIsNull() {
            addCriterion("`tactics_remark` is null");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkIsNotNull() {
            addCriterion("`tactics_remark` is not null");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkEqualTo(String value) {
            addCriterion("`tactics_remark` =", value, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkNotEqualTo(String value) {
            addCriterion("`tactics_remark` <>", value, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkGreaterThan(String value) {
            addCriterion("`tactics_remark` >", value, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`tactics_remark` >=", value, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkLessThan(String value) {
            addCriterion("`tactics_remark` <", value, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkLessThanOrEqualTo(String value) {
            addCriterion("`tactics_remark` <=", value, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkLike(String value) {
            addCriterion("`tactics_remark` like", value, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkNotLike(String value) {
            addCriterion("`tactics_remark` not like", value, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkIn(List<String> values) {
            addCriterion("`tactics_remark` in", values, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkNotIn(List<String> values) {
            addCriterion("`tactics_remark` not in", values, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkBetween(String value1, String value2) {
            addCriterion("`tactics_remark` between", value1, value2, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andTacticsRemarkNotBetween(String value1, String value2) {
            addCriterion("`tactics_remark` not between", value1, value2, "tacticsRemark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("`creator` is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("`creator` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("`creator` =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("`creator` <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("`creator` >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("`creator` >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("`creator` <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("`creator` <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("`creator` like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("`creator` not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("`creator` in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("`creator` not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("`creator` between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("`creator` not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("`updater` is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("`updater` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("`updater` =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("`updater` <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("`updater` >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("`updater` >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("`updater` <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("`updater` <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("`updater` like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("`updater` not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("`updater` in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("`updater` not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("`updater` between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("`updater` not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("`deleteflag` is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("`deleteflag` is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("`deleteflag` =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("`deleteflag` <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("`deleteflag` >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("`deleteflag` >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("`deleteflag` <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("`deleteflag` <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("`deleteflag` in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("`deleteflag` not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("`deleteflag` between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("`deleteflag` not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tactics_record
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 19 11:36:08 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}