package com.jzfq.rms.product.persistence.dao;

import com.jzfq.rms.product.bean.CheckItems;
import com.jzfq.rms.product.bean.CheckItemsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ICheckItemsDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    long countByExample(CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    int deleteByPrimaryKey(Integer checkItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    int insert(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    int insertSelective(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    List<CheckItems> selectByExample(CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    CheckItems selectByPrimaryKey(Integer checkItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") CheckItems record, @Param("example") CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    int updateByExample(@Param("record") CheckItems record, @Param("example") CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    int updateByPrimaryKeySelective(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated Thu Nov 09 14:47:42 CST 2017
     */
    int updateByPrimaryKey(CheckItems record);
}