package com.jzfq.rms.product.persistence.dao;

import com.jzfq.rms.product.bean.Dictionary;
import com.jzfq.rms.product.bean.DictionaryExample;
import com.jzfq.rms.product.bean.TacticsRecord;
import com.jzfq.rms.product.common.PageParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface IDictionaryDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    long countByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    List<Dictionary> selectByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    Dictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    int updateByExample(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Tue Oct 17 15:23:41 CST 2017
     */
    int updateByPrimaryKey(Dictionary record);

    List<Map<String, Object>> getDictionary(DictionaryExample example);

    String getValue(Map conditionMap);

    List<Map<String,Object>> queryList(PageParam<Dictionary> page);
}