package com.jzfq.rms.product.persistence.dao;

import com.jzfq.rms.product.bean.ProductInfo;
import com.jzfq.rms.product.bean.ProductInfoExample;
import com.jzfq.rms.product.common.PageParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface IProductInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    long countByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    List<ProductInfo> selectByExampleWithBLOBs(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    List<ProductInfo> selectByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    ProductInfo selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int updateByExample(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Thu Nov 16 14:12:04 CST 2017
     */
    int updateByPrimaryKey(ProductInfo record);

    /**
     * 查询订单策略分页数据
     * @param page
     * @return
     */
    List<ProductInfo> queryList(PageParam<ProductInfo> page);

    int updateProductTacticsForFlag(String[] productIds);

    int checkProductName(Map<String, Object> params);

    String getProductOrderNo();
}