package com.jzfq.rms.product.persistence.dao;

import com.jzfq.rms.product.bean.RuleClassification;
import com.jzfq.rms.product.bean.RuleInfo;
import com.jzfq.rms.product.bean.RuleInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface IRuleInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    long countByExample(RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    int deleteByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    int insert(RuleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    int insertSelective(RuleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    List<RuleInfo> selectByExample(RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    RuleInfo selectByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") RuleInfo record, @Param("example") RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    int updateByExample(@Param("record") RuleInfo record, @Param("example") RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    int updateByPrimaryKeySelective(RuleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbg.generated Wed Nov 22 13:02:16 CST 2017
     */
    int updateByPrimaryKey(RuleInfo record);

    List<Map<String,Object>> getRuleClassiName(RuleInfoExample example);

    /**
     * 查询一级规则
     * @param example
     * @return
     */
    List<RuleClassification> getRuleClassificationFirst(RuleInfoExample example);

    /**
     * 根据parentNo查询二级规则
     * @param mapParam
     * @return
     */
    List<RuleClassification> getRuleClassificationSecond(Map<String,Object> mapParam);
}