package com.jzfq.rms.product.persistence.dao;

import com.alibaba.fastjson.JSONArray;
import com.jzfq.rms.product.bean.TacticsRecord;
import com.jzfq.rms.product.bean.TacticsRecordExample;
import com.jzfq.rms.product.common.PageParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ITacticsRecordDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    long countByExample(TacticsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int deleteByPrimaryKey(Integer tacticsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int insert(TacticsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int insertSelective(TacticsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    List<TacticsRecord> selectByExampleWithBLOBs(TacticsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    List<TacticsRecord> selectByExample(TacticsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    TacticsRecord selectByPrimaryKey(String tacticsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") TacticsRecord record, @Param("example") TacticsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TacticsRecord record, @Param("example") TacticsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int updateByExample(@Param("record") TacticsRecord record, @Param("example") TacticsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int updateByPrimaryKeySelective(TacticsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TacticsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tactics_record
     *
     * @mbg.generated Tue Dec 19 11:36:08 CST 2017
     */
    int updateByPrimaryKey(TacticsRecord record);

    /**
     * 查询策略分页数据
     * @param page
     * @return
     */
    List<TacticsRecord> queryList(PageParam<TacticsRecord> page);

    int updateTacticsState(@Param("tacticsIds") List<Integer> tacticsIds, @Param("tacticsState")String tacticsState, @Param("updater")String updater);

    int checkTacticsName(Map<String,Object> params);

    String getTacticsNo(Integer tacticsType);

    String selectNameByNo(String tacticsNo);

    String getRuleParamNo(String tacticsNo);
}